IF
	Global("s#XGthf","GLOBAL",1)
	!Global("XGthfQuestDone","GLOBAL",1)
	PartyHasItem("XGBOOT4")
	Global("XGBOOT4","MYAREA",0)
THEN
  RESPONSE #100
		SetGlobal("XGBOOT4","MYAREA",1)
		AddJournalEntry(@51704,QUEST)
END

IF
	!Global("s#XGthf","GLOBAL",1)
	!Global("XGthfQuestDone","GLOBAL",1)
	PartyHasItem("XGBOOT4")
	Global("XGBOOT4","MYAREA",0)
THEN
  RESPONSE #100
		SetGlobal("XGBOOT4","MYAREA",1)
		AddJournalEntry(@51708,QUEST)
END

IF
  Global("RevealXG0072","XG0072",0)
  PartyHasItem("XGartk1")
THEN
  RESPONSE #100
    SetGlobal("RevealXG0072","XG0072",1)
    ClearAllActions()
    StartCutSceneMode()
	FadeFromColor([5.0],0)
    CreateCreature("XGprq",[828.1370],10)
    Wait(3)
    ActionOverride("XGprq",StartDialogue("XGprc1",Player1))
    EndCutSceneMode()
END

IF
  Global("XGDEAD0","XG0072",0)
  Dead("XGprq")
  PartyHasItem("XGartk1")
THEN
  RESPONSE #100
    SetGlobal("XGDEAD0","XG0072",1)
    Wait(1)
    StartCutSceneMode()
    CreateCreature("XGBHC",[1339.1489],0)
    ActionOverride("XGBHC",MoveToPoint([1040.1334]))
    Wait(6)
    ActionOverride(Player1,MoveToPoint([916.1288]))
    DisplayStringHead(Player1,@0)  
    Wait(5)
    DisplayStringHead("XGBHC",@1)  
    Wait(6)
    TakePartyItem("XGARTK1")
    GiveItemCreate("MISC07",Player1,5000,0,0) 
    GiveItemCreate("XGFALX5",Player1,0,0,0)
    ActionOverride("XGBHC",EscapeArea())
    EraseJournalEntry(@50702) 
    EraseJournalEntry(@50703)  
    EraseJournalEntry(@50704)  
    EraseJournalEntry(@50705)  
    EraseJournalEntry(@50706)  
	AddJournalEntry(@50701,QUEST_DONE)
    EndCutSceneMode()
END

