IF
  OnCreation()
  Global("EnteredXG0019","XG0019",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredXG0019","XG0019",1)
    ClearAllActions()
    StartCutSceneMode()
    HideGUI()
    Wait(3)
    CreateCreatureDoor("XGYARPN",[457.1821],4)
    Wait(3)
    DisplayString("XGYARPN",@0)  // @0
    Wait(3)
    ActionOverride("XGYARPN",EscapeArea())
    RevealAreaOnMap("XG0319")
    Wait(2)
    UnhideGUI()
    EndCutSceneMode()
    Wait(1)
END

