IF
	OnCreation()
	PartyHasItem("XGMISC")  // ~Назначение~
THEN
	RESPONSE #100
		ClearAllActions()
		StartCutSceneMode()
		FadeFromColor([20.0],0)
		Wait(3)
		Explore()
		CreateCreature("XGNEAN28",[1734.1869],14)
		MoveViewPoint([1883.1939],FAST)
		HideGUI()
		PlaySound("XGNWN2")
		CreateCreature("XGAMAG",[1734.1869],14)  // ~Главный архимаг~
		CreateCreature("XGRADAK",[1822.1920],6)  // ~Градак~
		CreateCreature("XGFALCO",[1807.1995],8)  // ~Графалкон~
		CreateCreature("XGCELM",[1619.1897],12)  // ~Элминстер~
		CreateCreature("XGCADEP",[1663.2078],10)  // ~Паладин культа~
		CreateCreature("XGCADEP",[1873.2138],6)  // ~Паладин культа~
		CreateCreature("XGCADEP",[2068.2094],6)  // ~Паладин культа~
		CreateCreature("XGCADEP",[2170.1964],4)  // ~Паладин культа~
		CreateCreature("XGCADEP",[2116.1816],2)  // ~Паладин культа~
		CreateCreature("XGCADEP",[1924.1736],2)  // ~Паладин культа~
		Wait(3)
		DisplayString("XGAMAG",@0)  
		Wait(4)
		DisplayString("XGAMAG",@1)  
		Wait(8)
		DisplayString("XGRADAK",@2)  
		Wait(4)
		CreateVisualEffectObject("SPROTECT","XGAMAG")
		Wait(1)
		CreateVisualEffectObject("SPROTECT","XGAMAG")
		Wait(1)
		CreateVisualEffectObject("SPROTECT","XGAMAG")
		Wait(1)
		ActionOverride("XGAMAG",ForceSpell("XGRADAK",WIZARD_TRUE_SIGHT))
		Wait(6)
		CreateVisualEffectObject("SPROTECT","XGRADAK")
		PlaySound("EFF_M23C")
		ActionOverride("XGAMAG",ForceSpell("XGRADAK",WIZARD_PROTECTION_FROM_ENERGY))
		Wait(6)
		CreateVisualEffectObject("SPROTECT","XGRADAK")
		PlaySound("EFF_M23C")
		ActionOverride("XGAMAG",ForceSpell("XGRADAK",WIZARD_ABSOLUTE_IMMUNITY))
		Wait(6)
		CreateVisualEffectObject("SPROTECT","XGRADAK")
		PlaySound("EFF_M23C")
		ActionOverride("XGAMAG",ForceSpell("XGRADAK",WIZARD_PROTECTION_FROM_ENERGY))
		Wait(6)
		CreateVisualEffectObject("SPROTECT","XGRADAK")
		PlaySound("EFF_M23C")
		Wait(1)
		ScreenShake([20.20],10)
		Wait(3)
		DisplayString("XGRADAK",@3)
		Wait(1)
		CreateCreatureDoor("XGYARP11",[1425.2037],6)  // ~Градаковский воин~
		CreateCreatureDoor("XGYARP12",[1633.2180],6)  // ~Градаковский воин~
		CreateCreatureDoor("XGYARP13",[1498.2186],4)  // ~Градаковский воин~
		CreateCreatureDoor("XGYARP14",[1633.2180],4)  // ~Градаковский воин~
		CreateCreatureDoor("XGYARPW7",[2068.2094],6)  
		CreateCreatureDoor("XGYARPW8",[2170.1964],4)  
		CreateCreatureDoor("XGYARPW9",[2116.1816],2)  
		CreateCreatureDoor("XGYARP10",[2200.1800],2)
		Wait(3)
		ActionOverride("XGRADAK",MoveToPoint([1177.2047]))
		Wait(2)
		ActionOverride("XGFALCO",MoveToPoint([1177.2047]))
		DisplayString("XGFALCO",@6) 
		Wait(1)
		DisplayString("XGCELM",@4)  
		Wait(2)
		ActionOverride("XGCELM",MoveToPoint([1177.2047]))
		ActionOverride("XGAMAG",ReallyForceSpell(Myself,DRYAD_TELEPORT))
		Wait(2)
		ActionOverride("XGRADAK",EscapeArea()) 
		Wait(2)
		ActionOverride("XGFALCO",EscapeArea())
		Wait(1)
		ActionOverride("XGCELM",EscapeArea())
		TakePartyItem("XGMISC")
		Wait(1)
		UnhideGUI()
		EndCutSceneMode()
END

IF
	Dead("XGYARP11")
	Dead("XGYARP12")
	Dead("XGYARP13")
	Dead("XGYARP14")  
	Global("XGpursuit0053","XG0053",0)
THEN
	RESPONSE #100
		ClearAllActions()
		StartCutSceneMode()
		HideGUI()
		Wait(1)
		CreateCreatureDoor("XGELWIN",[2400.2240],3)
		ActionOverride(Player1,MoveToPoint([2120.2240]))
		Wait(4)
		ActionOverride("XGNEAN28",DestroySelf())
		DisplayStringHead("XGELWIN",@5)
		Wait(4)
		//HideAreaOnMap("XG0053") // Maybe not hide it
		SetGlobal("XGpursuit0053","XG0053",1)
		ActionOverride(Player1,ReallyForceSpell(Myself,DRYAD_TELEPORT))
		ActionOverride(Player2,ReallyForceSpell(Myself,DRYAD_TELEPORT))
		ActionOverride(Player3,ReallyForceSpell(Myself,DRYAD_TELEPORT))
		ActionOverride(Player4,ReallyForceSpell(Myself,DRYAD_TELEPORT))
		ActionOverride(Player5,ReallyForceSpell(Myself,DRYAD_TELEPORT))
		ActionOverride(Player6,ReallyForceSpell(Myself,DRYAD_TELEPORT))
		Wait(2)
		FadeToColor([50.0],0)
		Wait(3)
		ActionOverride(Player1,LeaveAreaLUA("XG0054","",[3380.810],3))
		ActionOverride(Player2,LeaveAreaLUA("XG0054","",[3380.750],3))
		ActionOverride(Player3,LeaveAreaLUA("XG0054","",[3380.870],3))
		ActionOverride(Player4,LeaveAreaLUA("XG0054","",[3300.810],3))
		ActionOverride(Player5,LeaveAreaLUA("XG0054","",[3300.750],3))
		ActionOverride(Player6,LeaveAreaLUA("XG0054","",[3300.870],3))
		ActionOverride("XGELWIN",DestroySelf())
		EndCutSceneMode()
END


IF
	Dead("XGCG")
THEN
	RESPONSE #100
		ClearAllActions()
		StartCutSceneMode()
		HideGUI()
		Wait(1)
		CreateCreatureObjectDoor("XGELWIN","XGCG",0,0,0)
		Wait(1)
		CreateVisualEffectObject("SPPORTAL","XGCG")
		Wait(2)
		CreateCreatureObject("XGRADAK","XGCG",0,0,0)
		CreateCreatureObject("XGFALCO","XGCG",0,0,0)
		Wait(1)
		ActionOverride("XGFALCO",MoveToObjectNoInterrupt(Player1))
		Wait(2)
		DisplayStringHead("XGRADAK",@7)  
		Wait(5)
		DisplayStringHead("XGELWIN",@8)  
		Wait(3)
		DisplayStringHead("XGFALCO",@9)
		Wait(2)
		ActionOverride("XGFALCO",Attack(Player1))
		Wait(1)
		Kill(Player1)
		Wait(2)
		EndCutSceneMode()
END


/*
IF
	OR(4)
		Exists("XGYARPW7")
		Exists("XGYARPW8")
		Exists("XGYARPW9")
		Exists("XGYARP10")
	Global("XGpursuit0053","XG0053",1)
THEN
	RESPONSE #100
		SetGlobal("XGpursuit0053","XG0053",2)
		ActionOverride("XGYARPW7",ChangeEnemyAlly(Myself,NEUTRAL))
	    ActionOverride("XGYARPW9",ChangeEnemyAlly(Myself,NEUTRAL))
	    ActionOverride("XGYARPW9",ChangeEnemyAlly(Myself,NEUTRAL))
	    ActionOverride("XGYARP10",ChangeEnemyAlly(Myself,NEUTRAL))
		Wait(3)
		ActionOverride("XGYARPW7",MoveToPointNoInterrupt([2120.2240]))
		ActionOverride("XGYARPW9",MoveToPointNoInterrupt([2120.2240]))
		ActionOverride("XGYARPW9",MoveToPointNoInterrupt([2120.2240]))
		ActionOverride("XGYARP10",LeaveAreaLUA("XG0054","",([2120.2240]))
		SetGlobal("XGfound0053","XG0053",1)
END

IF
	Exists("XGYARPW7")
	Global("XGYARPW7","XG0053",0)
END
THEN
	RESPONSE #100
		IncrementGlobal("XGcount0053","XG0053",1)	
		SetGlobal("XGYARPW7","XG0053",1)
END

IF
	Exists("XGYARPW8")
	Global("XGYARPW8","XG0053",0)
THEN
	RESPONSE #100
		IncrementGlobal("XGcount0053","XG0053",1)	
		SetGlobal("XGYARPW8","XG0053",1)
END

IF
	Exists("XGYARPW9")
	Global("XGYARPW9","XG0053",0)
THEN
	RESPONSE #100
		IncrementGlobal("XGcount0053","XG0053",1)	
		SetGlobal("XGYARPW9","XG0053",1)
END

IF
	Exists("XGYARP10")
	Global("XGYARP10","XG0053",0)
THEN
	RESPONSE #100
		IncrementGlobal("XGcount0053","XG0053",1)	
		SetGlobal("XGYARP10","XG0053",1)
END


// Fidel ask for help


IF
	Global("XGpursuit0053","XG0053",2)
THEN
	RESPONSE #100
		CreateCreature("XG.....",[2400.2240],3)
		SetGlobal("XGpursuit0053","XG0053",3)
END

*/
/*
IF
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		StartDialogueNoSet(LastSeenBy)
END

IF ~Global("XGpursuit0053","XG0053",3)~ THEN BEGIN 0
  SAY ~~
  IF ~Global("XGcount0053","XG0053",1)~ THEN REPLY ~~  GOTO 1
  IF ~Global("XGcount0053","XG0053",2)~ THEN REPLY ~~  GOTO 2
  IF ~Global("XGcount0053","XG0053",3)~ THEN REPLY ~~  GOTO 3
  IF ~Global("XGcount0053","XG0053",4)~ THEN REPLY ~~  GOTO 4
END

IF ~~ THEN BEGIN 1
  SAY ~~
  IF ~~ THEN REPLY ~~ DO ~AddJournalEntry(~~,QUEST) SetGlobal("XGpursuit0053","XG0053",4)~ EXIT
END

IF ~~ THEN BEGIN 2
  SAY ~~
  IF ~~ THEN REPLY ~~ DO ~AddJournalEntry(~~,QUEST) SetGlobal("XGpursuit0053","XG0053",4)~ EXIT
END

IF ~~ THEN BEGIN 3
  SAY ~~
  IF ~~ THEN REPLY ~~ DO ~AddJournalEntry(~~,QUEST) SetGlobal("XGpursuit0053","XG0053",4)~ EXIT
END

IF ~~ THEN BEGIN 4
  SAY ~~
  IF ~~ THEN REPLY ~~ DO ~AddJournalEntry(~~,QUEST) SetGlobal("XGpursuit0053","XG0053",4)~ EXIT
END

IF ~Global("XGpursuit0053","XG0053",4)~ THEN BEGIN 5
  SAY ~~
  IF ~Global("XGcount0053","XG0053",1)
		Dead("XGYARPW7")
		Dead("XGYARPW8")
		Dead("XGYARPW9")
		Dead("XGYARP10")~ THEN REPLY ~~  GOTO 6
  IF ~Global("XGcount0053","XG0053",2)
		Dead("XGYARPW7")
		Dead("XGYARPW8")
		Dead("XGYARPW9")
		Dead("XGYARP10")~ THEN REPLY ~~  GOTO 6
  IF ~Global("XGcount0053","XG0053",3)
		Dead("XGYARPW7")
		Dead("XGYARPW8")
		Dead("XGYARPW9")
		Dead("XGYARP10")~ THEN REPLY ~~  GOTO 6
  IF ~Global("XGcount0053","XG0053",4)
		Dead("XGYARPW7")
		Dead("XGYARPW8")
		Dead("XGYARPW9")
		Dead("XGYARP10")~ THEN REPLY ~~  GOTO 6
  IF ~~ THEN REPLY ~~  GOTO 7
END

IF ~~ THEN BEGIN 6
  SAY ~~
  IF ~~ THEN DO ~AddJournalEntry(~~,QUEST_DONE) SetGlobal("XGpursuit0053","XG0053",5)~ EXIT
END

IF ~~ THEN BEGIN 7
  SAY ~~
  IF ~~ THEN EXIT
END

IF ~Global("XGpursuit0053","XG0053",5)~ THEN BEGIN 8
  SAY ~Salut~
  IF ~~ THEN EXIT
END

// On the run script and dialog

IF
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		StartDialogueNoSet(LastSeenBy)
END


IF ~Global("XGfound0053","XG0053",1) THEN BEGIN 1
  SAY ~~
  IF ~~ THEN REPLY ~~  DO ~Enemy~  EXIT
END



*/