IF
	OnCreation()
	Global("EnteredXG0018","XG0018",0)
THEN
	RESPONSE #100
		SetGlobal("EnteredXG0018","XG0018",1)
		ClearAllActions()
		StartCutSceneMode()
		HideGUI()
		CreateCreature("XGYARPN",[667.1017],0) 
		CreateCreature("XGYARPW",[1124.874],0) 
		CreateCreature("XGYARPW",[1148.967],0) 
		CreateCreature("XGYARPW",[1174.1083],0)
		CreateCreature("XGYARPW",[1278.1086],0)
		CreateCreature("XGYARPW",[1285.1014],0)
		CreateCreature("XGYARPW",[1284.937],0) 
		CreateCreature("XGYARPW",[1501.958],0) 
		CreateCreature("XGYARPA",[1435.783],0) 
		CreateCreature("XGYARPA",[1538.795],0) 
		CreateCreature("XGYARPA",[1688.821],0) 
		CreateCreature("XGYARPA",[1711.750],0) 
		FadeFromColor([20.0],0)
		ScreenShake([20.20],10)
		Wait(3)
		DisplayStringHead("XGYARPN",@1)  // @1
		Wait(6)
		ActionOverride("XGYARPN",EscapeArea())
		Wait(2)
		UnhideGUI()
		EndCutSceneMode()
END

