IF
	Global("XG0034_XG0020","MYAREA",0)
	Global("XGPoFinBG","GLOBAL",1)
THEN
	RESPONSE #100
		ClearAllActions()
		StartCutSceneMode()
		AdvanceTime(ONE_DAY)
		MoveViewObject(Player1,INSTANT)
		FadeFromColor([30.0],0)
		Wait(3)
		DisplayStringHead(Player1,@0)
		UnhideGUI()
		EndCutSceneMode()
		SetGlobal("XG0034_XG0020","MYAREA",1)
END

IF
	Global("XG1120_XG0020","GLOBAL",1)
	InMyArea(Player1)
THEN
	RESPONSE #100
		ClearAllActions()
		StartCutSceneMode()
		MoveViewObject(Player1,INSTANT)
		FadeFromColor([50.0],0)
		SetGlobal("XG1120_XG0020","GLOBAL",2)
		CreateCreatureObject("XGBGG",Player1,0,0,0)
		Wait(1)
		UnhideGUI()
		EndCutSceneMode()
END

// Acces to NBaldursGate_TempleofHelm (XG0020.ARE only) 

IF
	Global("s#XGBLMAJ","GLOBAL",0)
	Global("XG0420_XG0020_Close","MYAREA",0)
THEN
  RESPONSE #100
		SetGlobal("XG0420_XG0020_Close","MYAREA",1)
		SetGlobal("XG0420_XG0020_Open","MYAREA",0)
		TriggerActivation("Door0002",FALSE)
END

IF
	!Global("s#XGBLMAJ","GLOBAL",0)
	Global("XG0420_XG0020_Open","MYAREA",0)
THEN
  RESPONSE #100
		SetGlobal("XG0420_XG0020_Close","MYAREA",0)
		SetGlobal("XG0420_XG0020_Open","MYAREA",1)
		TriggerActivation("Door0002",TRUE)
END

IF
	Global("Reveal0020","MYAREA",0)
	PartyHasItem("XGZAT2")
	AreaCheck("XG0020")
	InMyArea(Player1)
THEN
  RESPONSE #100
    SetGlobal("Reveal0020","MYAREA",1)
    StartCutSceneMode()
    HideGUI()
    CreateCreature("XGASF2BG",[3390.1570],8)
    CreateCreature("XGASF1BG",[3524.1624],8)
    CreateCreature("XGASSBG",[3639.1627],8)
		Wait(1)
    DisplayStringHead("XGASF2BG",@1)
		Wait(1)
    DisplayStringHead("XGASSBG",@2)
		Wait(1)
    DisplayStringHead("XGASF1BG",@3)
		Wait(2)
    TakePartyItem("XGZAT2")
    GiveItemCreate("XGZAT3",Player1,0,0,0)
    UnhideGUI()
    EndCutSceneMode()
END

IF
	Global("XGPoFinBG","GLOBAL",1)
	Global("XGPoFXGMIL","MYAREA",0)
	AreaCheck("XG0020")
THEN
	RESPONSE #100
		CreateCreature("XGMIL",[3840.2483],14)  // Milicien
		CreateCreature("XGMIL",[3920.2062],8)  // Milicien
		CreateCreature("XGMIL",[4368.1547],2)  // Milicien
		CreateCreature("XGMIL",[3642.1484],0)  // Milicien
		CreateCreature("XGMIL",[2559.1320],14)  // Milicien
		CreateCreature("XGMIL",[328.1512],14)  // Milicien
		CreateCreature("XGMIL",[134.1603],14)  // Milicien
		CreateCreature("XGMIL",[2155.2838],2)  // Milicien
		CreateCreature("XGTDR",[1449.1155],0)  // Pretre
		CreateCreature("XGTDR",[1662.1154],0)  // Pretre
		CreateCreature("xgtanadv",[3195.1065],0)  // Aventurier
		SetGlobal("XGPoFXGMIL","MYAREA",1)
		Continue()
END

IF
	Global("XGPoFinBG","GLOBAL",1)
	Global("XGBGFL00","MYAREA",0)
	RandomNum(2,1)
THEN
	RESPONSE #100
		SetGlobal("XGFLAM12_ishere","MYAREA",1)
		SetGlobal("XGBGFL00","MYAREA",1)
		Wait(2)
		CreateCreatureObject("XGFLAM12",Player1,0,0,0)
END

IF
	Global("XGPoFinBG","GLOBAL",1)
	Global("XGBGFL00","MYAREA",0)
	RandomNum(2,2)
THEN
	RESPONSE #100
		SetGlobal("XGFLAF12_ishere","MYAREA",1)
		SetGlobal("XGBGFL00","MYAREA",1)
		Wait(2)
		CreateCreatureObject("XGFLAF12",Player1,0,0,0)
END

IF
	Global("XGBGG_Missing","GLOBAL",1)
	Global("XGFLAM12_ishere","MYAREA",1)
	InMyArea(Player1)
	PartyHasItem("XGZAT4")
THEN
	RESPONSE #100
		SetGlobal("XGFLAM12_ishere","MYAREA",2)
		SetGlobal("XGBGG_Missing","GLOBAL",2)
		ActionOverride("XGFLAM12",LeaveAreaLUA("XG0020","",[1148.2965],8))
		ActionOverride("XGFLAM12",MoveToObject(Player1))
		Wait(1)
		ActionOverride("XGFLAM12",StartDialogue("XGBGFL00",Player1))
END

IF
	Global("XGBGG_Missing","GLOBAL",1)
	Global("XGFLAF12_ishere","MYAREA",1)
	InMyArea(Player1)
	PartyHasItem("XGZAT4")
THEN
	RESPONSE #100
		SetGlobal("XGFLAF12_ishere","MYAREA",2)
		SetGlobal("XGBGG_Missing","GLOBAL",2)
		ActionOverride("XGFLAF12",LeaveAreaLUA("XG0020","",[1148.2965],8))
		ActionOverride("XGFLAF12",MoveToObject(Player1))
		Wait(1)
		ActionOverride("XGFLAF12",StartDialogue("XGBGFL00",Player1))
END

/*
IF
	Global("NEWGAME_SOA","GLOBAL",1)
	Global("XGPoFinBG","GLOBAL",1)
	AreaCheck("BG0200")
THEN
	RESPONSE #100
		StartCutSceneMode()
		HideGUI()
		ClearAllActions()
		FadeToColor([50.0],0)
		Wait(2)
		SetGlobal("NEWGAME_SOA","GLOBAL",1)
		ActionOverride(Player2,LeaveAreaLUA("XG0020","",[3782.3065],8))
		ActionOverride(Player1,LeaveAreaLUA("XG0020","",[3818.3026],8))
		ActionOverride(Player3,LeaveAreaLUA("XG0020","",[3877.3112],8))
		ActionOverride(Player4,LeaveAreaLUA("XG0020","",[3802.3159],8))
		ActionOverride(Player5,LeaveAreaLUA("XG0020","",[3660.3114],8))
		ActionOverride(Player6,LeaveAreaLUA("XG0020","",[3707.3156],8))
END
*/

/*
IF
	OR(2)
		Global("XGJOPEAS","GLOBAL",1)
		Global("NEWGAME_SOA","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("XGJOPEAS","GLOBAL",0)
		SetGlobal("NEWGAME_SOA","GLOBAL",0)
		//Wait(2)
		//FadeFromColor([20.0],0)
		//UnhideGUI()
		//EndCutSceneMode()
END
*/

/*
IF
	Global("XGPoFinBG","GLOBAL",1)
THEN
  RESPONSE #100
  TriggerActivation("EntranceXG0620",TRUE)
  	AddMapNote([2260.1047],@20)
  	AddMapNote([2769.1185],@21)
  	AddMapNote([2147.1737],@22)
  	AddMapNote([3116.2027],@23)
  	AddMapNote([3256.711],@24)
  	RemoveMapNote([2385.700],68997)
  	RemoveMapNote([2385.700],68997)
END

IF
	Global("XGPoFinBG","GLOBAL",0)
THEN
  RESPONSE #100
	TriggerActivation("EntranceXG0620",FALSE)
  	AddMapNote([3256.711],@24)
  	AddMapNote([3256.711],@24)
  	RemoveMapNote([2385.700],68997)
  	RemoveMapNote([2385.700],68997)
  	RemoveMapNote([2385.700],68997)
  	RemoveMapNote([2385.700],68997)
END
*/