IF
	OnCreation()
	Global("EnteredXG0054","XG0054",0)
THEN
	RESPONSE #100
		ClearAllActions()
		StartCutSceneMode()
		CreateCreature("XGelms",[3180.800],11)  // ~Элминстер~
		FadeFromColor([20.0],0)
		Wait(3)
		SetGlobal("EnteredXG0054","XG0054",1)
		DisplayStringHead("XGelms",@0)  
		Wait(4)
		ActionOverride("XGelms",ForceSpell("XGelms",DRYAD_TELEPORT))
		Wait(3)
		UnhideGUI()
		EndCutSceneMode()
END

