IF
  OnCreation()
  Global("EnteredXG0118","XG0118",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredXG0118","XG0118",1)
    ClearAllActions()
    StartCutSceneMode()
    HideGUI()
    Wait(2)
    ScreenShake([20.20],10)
    Wait(3)
    DisplayStringHead(Player1,@0)
    Wait(2)
    UnhideGUI()
    EndCutSceneMode()
END

IF
	Global("RevealXG0118","XG0118",0)
	Dead("XGyarqc")
THEN
	RESPONSE #100
		SetGlobal("RevealXG0118","XG0118",1)
		ClearAllActions()
		StartCutSceneMode()
		HideGUI()
		CreateCreatureDoor("XGYARPN",[2173.1963],0) 
		Wait(2)
		ActionOverride(Player1,MoveToPoint([2350.1960]))
		Wait(4)
		RevealAreaOnMap("XG0019")
		DisplayString("XGYARPN",@1)
		Wait(6)
		DisplayStringHead(Player1,@2)
		Wait(3)
		ActionOverride("XGYARPN",MoveToPoint([2247.1939]))
		Wait(1)
		ActionOverride("XGYARPN",Face(7))
		Wait(1)
		ActionOverride("XGYARPN",MoveBetweenAreas("XG0019",[348.1817],6))
		Wait(2)
		UnhideGUI()
		EndCutSceneMode()
END

