IF
  Global("EnteredXG0153","XG0153",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredXG0153","XG0153",1)
    StartCutSceneMode()
    HideGUI()
    Wait(1)
    ActionOverride(Player1,MoveToPoint([439.561]))
    Wait(2)
    DisplayStringHead("XGCELM",@0)  
    Wait(7)
    DisplayStringHead(Player1,@1)  
    Wait(8)
    DisplayStringHead("XGCELM",@2)  
    Wait(7)
    UnhideGUI()
    EndCutSceneMode()
END

