IF
	Global("s#XGELOR_XGARJUN","GLOBAL",5)
THEN
  RESPONSE #100
		ActionOverride("XGARJUN",ReallyForceSpell("XGARJUN",CLERIC_ZONE_OF_SWEET_AIR))
		Wait(2)
		ActionOverride(Player2,ReallyForceSpell(Player2,WIZARD_FLESH_TO_STONE_IGNORE_RESISTANCE))
		ActionOverride(Player3,ReallyForceSpell(Player3,WIZARD_DISINTEGRATE2_IGNORE_RESISTANCE))
		ActionOverride(Player4,ReallyForceSpell(Player4,CLERIC_FLAME_STRIKE))
		ActionOverride(Player5,ReallyForceSpell(Player5,WIZARD_DISINTEGRATE_IGNORE_RESISTANCE))
		ActionOverride(Player6,ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH_IGNORE_RESISTANCE))
		ActionOverride(Player1,ReallyForceSpellRES("SPWI299",Myself))
		DisplayStringHead("XGARJUN",~MOUAHAHAHA !!!~) 
		Wait(5)
		Kill(Player2)
		Kill(Player3)
		Kill(Player4)
		Kill(Player5)
		Kill(Player6)
		Wait(2)
		Kill(Player1)
END
