IF
  Global("XGELWIN_XG0256","XG0256",0)
THEN
  RESPONSE #100
    CreateCreature("XGELWIN",[3752.3051],6)  // ~Элвин~
	CreateCreatureObject("XGNEANT4","XGELWIN",0,0,0)
    SetGlobal("XGELWIN_XG0256","XG0256",1)
END

IF
  Global("RevealXG0256","XG0256",0)
  Dead("XGGSER")  // ~Главный стражник~
THEN
  RESPONSE #100
    SetGlobal("RevealXG0256","XG0256",1)
    ClearAllActions()
    StartCutSceneMode()
    HideGUI()
    Explore()
	CreateVisualEffectObject("SPPORTAL","XGGSER")
	CreateVisualEffectObject("SPPORTAL","XGELWIN")
    Wait(2)
    ActionOverride("XGELWIN",LeaveAreaLUA("XG0256","",[3421.2858],6))
    Wait(1)
    ActionOverride("XGELWIN",FaceObject(Player1))
    ActionOverride(Player1,FaceObject("XGELWIN"))
    Wait(1)
    MoveViewPoint([3421.2858],INSTANT)
    DisplayStringHead("XGELWIN",@0)  // @0
    Wait(5)
    DisplayStringHead("XGELWIN",@2)  // @2
    Wait(5)
    DisplayStringHead(Player1,@1)  // @1
    Wait(3)
	FadeToColor([50.0],0)
	Wait(2)
    ActionOverride("XGELWIN",EscapeArea())
    RevealAreaOnMap("XG0034")
    ActionOverride(Player2,LeaveAreaLUA("XG0034","",[880.783],6))
    ActionOverride(Player1,LeaveAreaLUA("XG0034","",[964.755],6))
    ActionOverride(Player3,LeaveAreaLUA("XG0034","",[1036.741],6))
    ActionOverride(Player4,LeaveAreaLUA("XG0034","",[930.869],6))
    ActionOverride(Player5,LeaveAreaLUA("XG0034","",[1012.849],6))
    ActionOverride(Player6,LeaveAreaLUA("XG0034","",[1099.835],6))
    EndCutSceneMode()
END

