IF
  Global("RevealXG0301","XG0301",0)
  Dead("XGVAMP")  // ~Вампир~
THEN
  RESPONSE #100
    SetGlobal("RevealXG0301","XG0301",1)
    ClearAllActions()
    Explore()
    StartCutSceneMode()
    HideGUI()
    Wait(2)
    CreateCreature("XGSWILL",[188.346],0)  // ~Сэр Уильям~
    Wait(2)
    ActionOverride(Player1,MoveToPoint([181.270]))
    Wait(3)
    UnhideGUI()
    EndCutSceneMode()
END

IF
  Global("RevealXG0301","XG0301",1)
  Dead("XGLORU")
THEN
  RESPONSE #100
    SetGlobal("RevealXG0301","XG0301",2)
    ClearAllActions()
    Explore()
    StartCutSceneMode()
    HideGUI()
    Wait(2)
    CreateCreature("XGSTGS",[112.291],0)
    CreateCreature("XGSDWSP",[114.245],0)
    Wait(2)
    DisplayString("XGSWILL",@0)
    Wait(4)
    EraseJournalEntry(@51901)
    AddJournalEntry(@51902,QUEST_DONE)
    AddexperienceParty(10000)
    GivePartyGold(2000)
    ActionOverride("XGSWILL",EscapeArea())
    ActionOverride("XGSTGS",EscapeArea())
    ActionOverride("XGSDWSP",EscapeArea())
    Wait(2)
    UnhideGUI()
    EndCutSceneMode()
END

