IF
  OnCreation()
  Global("EnteredXG0419","XG0419",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredXG0419","XG0419",1)
    ClearAllActions()
    StartCutSceneMode()
    HideGUI()
    CreateCreature("XGHC1",[1362.927],0)
    CreateCreature("XGYARPN",[1379.1089],0)
		CreateCreatureObject("XGNEAN28","XGHC1",0,0,0)
    PlaySound("XGF")
    Wait(1)
		MoveViewObject("XGHC1",INSTANT)
    Wait(3)
    DisplayString("XGYARPN",@0)  // @0
    Wait(4)
    DisplayString("XGHC1",@1)  // @1
    Wait(4)
    DisplayString("XGYARPN",@2)  // @2
    Wait(8)
    DisplayString("XGHC1",@3)  // @3
    Wait(4)
		ActionOverride("XGYARPN",MoveToPoint([1786.1126]))
    Wait(2)
		ActionOverride("XGYARPN",EscapeArea())
    DisplayString("XGHC1",@4)  // @4
	CreateCreatureOffScreen("XGELVWR",10)
	CreateCreatureOffScreen("XGELVCP",10)
	CreateCreatureOffScreen("XGELVCL",10)
	CreateCreatureOffScreen("XGELVWR",10)
    Wait(4)
    ScreenShake([20.20],20)
		ActionOverride("XGELVWR",MoveToPoint([980.1049]))
		ActionOverride("XGELVCP",MoveToPoint([986.1056]))
		ActionOverride("XGELVCL",MoveToPoint([1067.1133]))
		ActionOverride("XGELVWR",MoveToPoint([1147.1228]))
    Wait(5)
   // CreateCreature("XGELVWR",[902.987],10)  // ~Ёльфийский воин~
   // CreateCreature("XGELVCP",[986.1056],10)  // ~Ёльфийский капитан~
   // CreateCreature("XGELVCL",[1067.1133],10)  // ~Ёльфийский сектант~
   // CreateCreature("XGELVWR",[1147.1228],10)  // ~Ёльфийский воин~
    DisplayString("XGELVCP",@5)  // @5
    Wait(4)
    DisplayString("XGHC1",@6)  // @6
    Wait(4)
    ActionOverride("XGELVWR",Attack("XGHC1"))
    ActionOverride("XGELVCP",Attack("XGHC1"))
    ActionOverride("XGELVCL",Attack("XGHC1"))
    ActionOverride("XGELVWR",Attack("XGHC1"))
    PlaySound("EFF_M23C")
    CreateVisualEffectObject("SPROTECT","XGHC1")
    PlaySound("EFF_M23C")
    Wait(1)
    ActionOverride("XGHC1",ForceSpell("XGELVWR",WIZARD_DISINTEGRATE_IGNORE_RESISTANCE))
    Wait(6)
    CreateVisualEffectObject("SPROTECT","XGHC1")
    PlaySound("EFF_M23C")
    Wait(1)
    ActionOverride("XGHC1",ForceSpell("XGELVCP",WIZARD_FLESH_TO_STONE_IGNORE_RESISTANCE))
    Wait(6)
    CreateVisualEffectObject("SPROTECT","XGHC1")
    PlaySound("EFF_M23C")
    Wait(1)
    ActionOverride("XGHC1",ForceSpell("XGELVCL",WIZARD_FLESH_TO_STONE_IGNORE_RESISTANCE))
    Wait(6)
    CreateVisualEffectObject("SPROTECT","XGHC1")
    PlaySound("EFF_M23C")
    Wait(1)
    ActionOverride("XGHC1",ForceSpell("XGELVWR",WIZARD_FINGER_OF_DEATH_IGNORE_RESISTANCE))
		ActionOverride("XGHC1",ChangeEnemyAlly(Myself,NEUTRAL))
		ActionOverride(Player2,MoveToPoint([980.1049]))
		ActionOverride(Player1,MoveToPoint([986.1056]))
		ActionOverride(Player3,MoveToPoint([1067.1133]))
		ActionOverride(Player4,MoveToPoint([1147.1228]))
		ActionOverride(Player5,MoveToPoint([1100.1160]))
		ActionOverride(Player6,MoveToPoint([1120.1200]))
    Wait(9)
		UnhideGUI()
		ActionOverride("XGHC1",StartDialogNoSet("XGHC1"))
    EndCutSceneMode()
END

IF
  Global("RevealAreaXG0419","XG0419",0)
  Dead("XGHC1")  // ~јрхимаг~
THEN
  RESPONSE #100
    SetGlobal("RevealAreaXG0419","XG0419",1)
    ClearAllActions()
    StartCutSceneMode()
    HideGUI()
	CreateCreatureOffScreen("XGELWIN",10)
    SmallWait(2)
	ActionOverride("XGELWIN",MoveToObject(Player1))
    Wait(5)
    //DisplayString("XGELWIN",@7)  // @7
		UnhideGUI()
		ActionOverride("XGELWIN",StartDialogNoSet(Player1))
    EndCutSceneMode()
END


IF
  Global("RevealAreaXG0419","XG0419",1)
THEN
  RESPONSE #100
    SetGlobal("RevealAreaXG0419","XG0419",2)
    RevealAreaOnMap("XG0025")
    ForceSpell("XGELWIN",DRYAD_TELEPORT)
END

