IF
	Global("RevealXG0412","XG0412",0)
	PartyHasItem("XGAMUL3")  // ~Bozsky dar~
THEN
	RESPONSE #100
		SetGlobal("RevealXG0412","XG0412",1)
		ClearAllActions()
		StartCutSceneMode()
		HideGUI()
		Wait(2)
		Explore()
		CreateCreature("XGWMLPG",[1082.742],6)  // ~Ёлитный охранник~
		Wait(4)
		ActionOverride(Player1,MoveToPoint([993.710]))
		MoveViewPoint([1082.742],SLOW)
		Wait(8)
		DisplayStringHead("XGWMLPG",@0)
		SetGlobal("s#XGWML","GLOBAL",3)
		Wait(10)
		EraseJournalEntry(@51402)
		EraseJournalEntry(@51403)
		EraseJournalEntry(@51404)
		EraseJournalEntry(@51405)
		EraseJournalEntry(@51406)
		AddJournalEntry(@51401,QUEST_DONE)
		UnhideGUI()
		EndCutSceneMode()
END

