IF
	OnCreation()
	Global("EnteredXG1020","XG1020",0)
THEN
	RESPONSE #100
		SetGlobal("EnteredXG1020","XG1020",1)
		ClearAllActions()
		StartCutSceneMode()
		HideGUI()
		//CreateCreature("INVISABO",[496.2160],0)
		//ForceSpell("INVISABO",CUTSCENE_METEOR_SWARM)
		//CreateCreature("INVISABO",[986.2329],0)
		//ForceSpell("INVISABO",CUTSCENE_METEOR_SWARM)
		Wait(1)
		CreateCreatureDoor("XGBRMOC",[565.2472],0)
		Wait(5)
		ActionOverride("XGBRMOC",StartDialogue("XGBRMOC",Player1))
		UnhideGUI()
		EndCutSceneMode()
END

IF
	Global("EnteredXG1020","XG1020",1)
	Global("XGBRMOC_XG1020","XG1020",1)
THEN
	RESPONSE #100
		ClearAllActions()
		StartCutSceneMode()
		HideGUI()
		//ActionOverride("INVISABO",DestroySelf())
		CreateCreature("XGBRMO",[362.2419],0)
		CreateCreature("XGBRMIL",[662.2549],0)
		CreateCreature("XGBRMIL",[678.2050],0)
		CreateCreature("XGBRMIL",[993.2175],0)
		//ForceSpell("XGBRMOC",CUTSCENE_METEOR_SWARM)
		Wait(2)
		CreateVisualEffectObject("SPDIMNDR","XGBRMOC")
		Wait(2)
		PlaySound("XGSCRN4")
		ActionOverride("XGBRMOC",MoveBetweenAreas("XG1020",[2865.354],S))  // (PoF)  Temple de la fraternite, (Margul)
		Wait(4)
		CreateCreature("XGMIL",[558.2593],0)
		CreateCreature("XGMIL",[658.2641],0)
		CreateCreature("XGMIL",[477.2432],0)
		CreateCreature("XGMIL",[458.2477],0)
		CreateCreature("XGMIL",[587.2542],0)
		Wait(2)
		DisplayString("XGMIL",@5)  // @5
		Wait(4)
		SetGlobal("EnteredXG1020","XG1020",2)
		UnhideGUI()
		EndCutSceneMode()
END

IF
	Global("EnteredXG1020","XG1020",3)
	Global("XGBRMOC_XG1020","XG1020",1)
THEN
	RESPONSE #100
		ClearAllActions()
		StartCutSceneMode()
		HideGUI()
		SetGlobal("XGBRMOC_XG1020","XG1020",2)
		SmallWait(2)
		ActionOverride(Player2,ReallyForceSpell(Player2,HOLD_PARTY))  // SPIN863.SPL (No such index)
		ActionOverride(Player3,ReallyForceSpell(Player3,HOLD_PARTY))  // SPIN863.SPL (No such index)
		ActionOverride(Player4,ReallyForceSpell(Player4,HOLD_PARTY))  // SPIN863.SPL (No such index)
		ActionOverride(Player5,ReallyForceSpell(Player5,HOLD_PARTY))  // SPIN863.SPL (No such index)
		ActionOverride(Player6,ReallyForceSpell(Player6,HOLD_PARTY))  // SPIN863.SPL (No such index)
		Wait(1)
		CreateVisualEffectObject("SPDIMNDR",Player2)
		CreateVisualEffectObject("SPDIMNDR",Player3)
		CreateVisualEffectObject("SPDIMNDR",Player4)
		CreateVisualEffectObject("SPDIMNDR",Player5)
		CreateVisualEffectObject("SPDIMNDR",Player6)
		Wait(2)
		ActionOverride(Player2,LeaveAreaLUA("XG1020","",[2837.172],12))
		ActionOverride(Player3,LeaveAreaLUA("XG1020","",[2902.173],12))
		ActionOverride(Player4,LeaveAreaLUA("XG1020","",[2986.195],12))
		ActionOverride(Player5,LeaveAreaLUA("XG1020","",[3050.231],12))
		ActionOverride(Player6,LeaveAreaLUA("XG1020","",[3095.280],12))
		Wait(5)
		ActionOverride("XGBRMOC",Enemy())
		UnhideGUI()
		EndCutSceneMode()
END

IF
	Dead("XGBRMOC")
	Global("XGBRMOC_Body","XG1020",0)
THEN
	RESPONSE #100
		Wait(2)
		DisplayStringHead(Player1,@6)
		SetGlobal("XGBRMOC_Body","XG1020",1)
		Wait(3)
		ActionOverride(Player1,ReallyForceSpell(Player2,NOHOLD_PARTY))
		ActionOverride(Player1,ReallyForceSpell(Player3,NOHOLD_PARTY))
		ActionOverride(Player1,ReallyForceSpell(Player4,NOHOLD_PARTY))
		ActionOverride(Player1,ReallyForceSpell(Player5,NOHOLD_PARTY))
		ActionOverride(Player1,ReallyForceSpell(Player6,NOHOLD_PARTY))
		Wait(2)
		DisplayStringHead(Player1,@7)
END

IF
	Global("XG1020_XG0720","XG1020",0)
	PartyHasItem("XGMRBO")
THEN
	RESPONSE #100
		SetGlobal("XG1020_XG0720","XG1020",1)
		ClearAllActions()
		StartCutSceneMode()
		HideGUI()
		FadeToColor([20.0],0)
		Wait(1)
		ActionOverride(Player1,ForceSpell(Player1,DRYAD_TELEPORT)
		ActionOverride(Player2,ForceSpell(Player2,DRYAD_TELEPORT)
		ActionOverride(Player3,ForceSpell(Player3,DRYAD_TELEPORT)
		ActionOverride(Player4,ForceSpell(Player4,DRYAD_TELEPORT)
		ActionOverride(Player5,ForceSpell(Player5,DRYAD_TELEPORT)
		ActionOverride(Player6,ForceSpell(Player6,DRYAD_TELEPORT)
		Wait(1)
		ActionOverride(Player1,LeaveAreaLUA("XG0720","",[1000.750],0))
		ActionOverride(Player2,LeaveAreaLUA("XG0720","",[1034.643],0))
		ActionOverride(Player3,LeaveAreaLUA("XG0720","",[1144.720],0))
		ActionOverride(Player4,LeaveAreaLUA("XG0720","",[956.718],0))
		ActionOverride(Player5,LeaveAreaLUA("XG0720","",[1054.796],0))
		ActionOverride(Player6,LeaveAreaLUA("XG0720","",[1048.737],0))
		EndCutSceneMode()
END

