IF
  OnCreation()
  Global("EnteredXG1234","XG1234",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredXG1234","XG1234",1)
    ClearAllActions()
    PlaySound("XGMUS3")
    StartCutSceneMode()
    HideGUI()
    Explore()
    ActionOverride("XGFALC1",Attack("XGRADA1"))
    Wait(1)
    ActionOverride("XGRADA1",Attack("XGFALC1"))
    Wait(4)
    ActionOverride("XGEMAG1",ForceSpell("XGFALC1",WIZARD_SLOW))
    Wait(6)
    ActionOverride("XGEMAG2",ForceSpell("XGFALC1",WIZARD_LIGHTNING_BOLT))
    Wait(6)
    Wait(4)
    DisplayString("XGRADA1",@0)  // @0
    Wait(6)
    Wait(3)
    DisplayString("XGFALC1",@1)  // @1
    Wait(6)
    Wait(3)
    ActionOverride("XGEMAG1",ForceSpell("XGFALC1",WIZARD_FEEBLEMIND))
    Wait(6)
    ActionOverride("XGEMAG2",ForceSpell("XGFALC1",WIZARD_CONFUSION))
    Wait(6)
    Wait(3)
    ScreenShake([20.20],40)
    CreateCreature("XGELWIN",[834.906],0)  // ~Элвин~
    Wait(2)
    ActionOverride("XGRADA1",Kill("XGFALC1"))
    Wait(1)
    DisplayString("XGELWIN",@2)  // @2
    Wait(1)
    ActionOverride("XGELWIN",ForceSpell("XGRADA1",WIZARD_CHAIN_LIGHTNING))
    Wait(6)
    ActionOverride("XGELWIN",ForceSpell("XGRADA1",WIZARD_MAGIC_MISSILE))
    ActionOverride("XGEMAG1",MoveToPoint([811.963]))
    ActionOverride("XGEMAG2",MoveToPoint([871.978]))
    Wait(5)
    ActionOverride("XGEMAG1",ForceSpell("XGELWIN",WIZARD_IMPRISONMENT))
    Wait(6)
    ForceSpell("XGEMAG2",DRYAD_TELEPORT)
    ForceSpell("XGEMAG1",DRYAD_TELEPORT)
    ForceSpell("XGELWIN",DRYAD_TELEPORT)
    Wait(4)
    FadeToColor([20.0],0)
    ActionOverride("XGRADA1",DestroySelf())
    CreateCreature("XGfngra",[676.1310],10)  // ~Градак~
    Wait(4)
    UnhideGUI()
    EndCutSceneMode()
END

IF
  Global("RevealXG1234","XG1234",0)
  Dead("XGfngra")  // ~Градак~
THEN
  RESPONSE #100
    SetGlobal("RevealXG1234","XG1234",1)
    StartCutSceneMode()
    FadeToColor([20.0],0)
    HideGUI()
    Explore()
    Wait(6)
    CreateCreature("XGCELM",[1027.1015],2)  // ~Элминстер~
    ScreenShake([20.20],3)
    Wait(6)
    ActionOverride(Player1,MoveToPoint([946.1058]))
    MoveViewPoint([1027.1015],SLOW)
    Wait(4)
    DisplayStringHead("XGCELM",@3)  // @3
    Wait(10)
    DisplayStringHead(Player1,@4)  // @4
    Wait(10)
    DisplayStringHead("XGCELM",@5)  // @5
    Wait(6)
    ForceSpell("XGCELM",DRYAD_TELEPORT)
    CreateCreature("XGELWIN",[1574.1142],2)  // ~Элвин~
    ActionOverride("XGELWIN",MoveToPoint([1122.1078]))
    Wait(6)
    DisplayStringHead("XGELWIN",@6)  // @6
    Wait(10)
    DisplayStringHead(Player1,@7)  // @7
    Wait(10)
    DisplayStringHead("XGELWIN",@8)  // @8
    Wait(10)
    DisplayStringHead("XGELWIN",@9)  // @9
    Wait(10)
    DisplayStringHead(Player1,@10)  // @10
    Wait(10)
    DisplayStringHead("XGELWIN",@11)  // @11
    Wait(10)
    DisplayStringHead("XGELWIN",@12)  // @12
    Wait(10)
    EraseJournalEntry(@51202)
    EraseJournalEntry(@51203)
    EraseJournalEntry(@51204)
    EraseJournalEntry(@51205)
    EraseJournalEntry(@51206)
    EraseJournalEntry(@51207)
    EraseJournalEntry(@51208)
    EraseJournalEntry(@51209)
    EraseJournalEntry(@51210)
    EraseJournalEntry(@51211)
    EraseJournalEntry(@51212)
    EraseJournalEntry(@51213)
    EraseJournalEntry(@51214)
    EraseJournalEntry(@51215)
    EraseJournalEntry(@51216)
    EraseJournalEntry(@51217)
    EraseJournalEntry(@51218)
    EraseJournalEntry(@51219)
    EraseJournalEntry(@51220)
    EraseJournalEntry(@51221)
    EraseJournalEntry(@51222)
    EraseJournalEntry(@51223)
    EraseJournalEntry(@51224)
	AddJournalEntry(@51201,QUEST_DONE)
    ReputationInc(2)
    GiveItemCreate("XGSUD07",Player1,0,0,0)  // ~Vyvazena sudlice~
    GiveItemCreate("XGGLAV5",Player1,0,0,0)  // ~Меч героев~
    GiveItemCreate("XGTRI7",Player1,0,0,0)  // ~Trojzubec krale Welsiona~
    GiveItemCreate("XGSTAR7",Player1,0,0,0)  // ~Шестичленная морская звезда~
    GiveItemCreate("XGFALH6",Player1,0,0,0)  // ~Тегродан~
    AddexperienceParty(21250)
    UnhideGUI()
    Wait(4)
    EndCutSceneMode()
    ActionOverride(Player2,LeaveAreaLUA("AR1602","",[356.727],8))
    ActionOverride(Player1,LeaveAreaLUA("AR1602","",[345.689],8))
    ActionOverride(Player3,LeaveAreaLUA("AR1602","",[316.708],8))
    ActionOverride(Player4,LeaveAreaLUA("AR1602","",[293.735],8))
    ActionOverride(Player5,LeaveAreaLUA("AR1602","",[342.763],8))
    ActionOverride(Player6,LeaveAreaLUA("AR1602","",[384.809],8))
END

