IF
	Opened([ANYONE])
	Global("XGDOOR17","XG0017",0)
THEN
	RESPONSE #100
		CreateCreature("XGELVW0",[2380.1772],0)
		CreateCreature("XGELVW0",[2380.1772],0)
		CreateCreature("XGELVW0",[2679.1929],0)
		CreateCreature("XGELVW0",[2679.1929],0)
		CreateCreature("XGELVW0",[2652.2437],0)
		CreateCreature("XGELVW0",[2652.2437],0)
		CreateCreature("XGELVW0",[2652.2437],0)
		CreateCreature("XGELVW0",[2652.2437],0)
		CreateCreature("XGSUEL0",[2533.1601],0)
		CreateCreature("XGSUEL0",[2679.1929],0)
		CreateCreature("XGSUEL0",[2679.1929],0)
		CreateCreature("XGSUEL0",[2380.1772],0)
		CreateCreature("XGSUEL0",[2380.1772],0)
		SetGlobal("XGDOOR17","XG0017",1)
END

//  CreateCreature("XGELIAH",[3160.2800],0)

// To see for making a cutscene for this