IF
	See([GOODCUTOFF])
	Global("XGMONOR_SHOUT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("XGMONOR_SHOUT","LOCALS",1)
		DisplayStringHead(Myself,@3004)
		FaceObject(Player1)
		Wait(10)
		DisplayStringHead(Myself,@3004)
		FaceObject(Player6)
		Wait(10)
		DisplayStringHead(Myself,@3004)
		FaceObject(Player2)
		Wait(10)
		DisplayStringHead(Myself,@3004)
		FaceObject(Player5)
		Wait(10)
		DisplayStringHead(Myself,@3004)
		FaceObject(Player3)
		Wait(10)
		DisplayStringHead(Myself,@3004)
		FaceObject(Player4)
		Continue()
END

IF
	Global("XGMONOR_SHOUT","LOCALS",1)
	Delay(20)
THEN
	RESPONSE #100
		SetGlobal("XGMONOR_SHOUT","LOCALS",0)
		Continue()
END


