IF
	See([GOODCUTOFF])
	Global("XGMO_SHOUT","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("XGMO_SHOUT","LOCALS",1)
		DisplayStringHead(Myself,@3000)
		FaceObject(Player1)
		Wait(5)
		DisplayStringHead(Myself,@3000)
		FaceObject(Player6)
		Wait(5)
		DisplayStringHead(Myself,@3000)
		FaceObject(Player2)
		Wait(5)
		DisplayStringHead(Myself,@3000)
		FaceObject(Player5)
		Wait(5)
		DisplayStringHead(Myself,@3000)
		FaceObject(Player3)
		Wait(5)
		DisplayStringHead(Myself,@3000)
		FaceObject(Player4)
		Continue()
END

IF
	Global("XGMO_SHOUT","LOCALS",1)
	Delay(20)
THEN
	RESPONSE #100
		SetGlobal("XGMO_SHOUT","LOCALS",0)
		Continue()
END
