////// Worldmap link for EET/BGT

// This addition allow to acces BG2 city gate in BG1, so don't do it !

/*
ACTION_IF GAME_IS ~eet~ AND FILE_EXISTS ~Paladins-of-Faerun/Worldmap/links.tbl~ BEGIN
			PRINT ~Link between Aeras for EET~
	COPY_EXISTING ~Paladins-of-Faerun/Worldmap/links.tbl~	~weidu_external/Paladins-of-Faerun/Worldmap/links.tbl~
		REPLACE_TEXTUALLY	~XG0020~	~BG0200~
	//	REPLACE_TEXTUALLY	~XG0120~	~BG0119~ // Useless
	//	REPLACE_TEXTUALLY	~XG0820~	~BG0121~ // Useless
	//	REPLACE_TEXTUALLY	~XG0520~	~BG0006~ // Useless
	//	REPLACE_TEXTUALLY	~XG0620~	~BG0111~ // Useless
	//	REPLACE_TEXTUALLY	~XG0320~	~BG0137~ // Useless
END


ACTION_IF GAME_IS ~bgt~ AND FILE_EXISTS ~Paladins-of-Faerun/Worldmap/links.tbl~ BEGIN
			PRINT ~Link between Aeras for BGT~
	COPY_EXISTING ~Paladins-of-Faerun/Worldmap/links.tbl~ ~weidu_external/Paladins-of-Faerun/Worldmap/links.tbl~
		REPLACE_TEXTUALLY	~XG0020~	~AR7300~
	//	REPLACE_TEXTUALLY	~XG0120~	~AR7219~ // Useless
	//	REPLACE_TEXTUALLY	~XG0820~	~AR7220~ // Useless
	//	REPLACE_TEXTUALLY	~XG0520~	~ARA006~ // Useless
	//	REPLACE_TEXTUALLY	~XG0620~	~AR7211~ // Useless
	//	REPLACE_TEXTUALLY	~XG0320~	~AR7237~ // Useless
END
*/

//////////////////////////////////
// Worldmap
//////////////////////////////////

	ACTION_IF FILE_EXISTS ~Worldmap/map_mods_areas.tbl~ THEN BEGIN

		COPY ~Worldmap/map_mods_areas.tbl~		~Worldmap~
			APPEND_FILE ~Paladins-of-Faerun/Worldmap/areas.tbl~

			/*	ACTION_IF GAME_IS ~bgt eet~ BEGIN
		COPY ~Worldmap/map_mods_links.tbl~		~Worldmap~
			APPEND_FILE ~weidu_external/Paladins-of-Faerun/Worldmap/links.tbl~
				END ELSE BEGIN	*/
		COPY ~Worldmap/map_mods_links.tbl~		~Worldmap~
			APPEND_FILE ~Paladins-of-Faerun/Worldmap/links.tbl~
			/*	END	*/

		COPY ~Worldmap/map_mods_trans.tra~		~Worldmap~
			APPEND_FILE_EVALUATE ~weidu_external/Paladins-of-Faerun/Languages/autotra/%LANGUAGE%/worldmap.tra~

	END ELSE BEGIN

		MKDIR ~Worldmap~

		COPY ~Paladins-of-Faerun/Worldmap/areas.tbl~							~Worldmap/map_mods_areas.tbl~

			/*	ACTION_IF GAME_IS ~bgt eet~ BEGIN
		COPY ~weidu_external/Paladins-of-Faerun/Worldmap/links.tbl~			~Worldmap/map_mods_links.tbl~
				END ELSE BEGIN	*/
		COPY ~Paladins-of-Faerun/Worldmap/links.tbl~							~Worldmap/map_mods_links.tbl~
		/*	END	*/

		COPY ~weidu_external/Paladins-of-Faerun/Languages/autotra/%LANGUAGE%/worldmap.tra~	~Worldmap/map_mods_trans.tra~

	END

// Append mastarea.2da with the new areas
	APPEND ~MASTAREA.2da~ ~XG0001 value~ UNLESS ~XG0001~ // Grotte des Marchands // Tradmith Cave //
	APPEND ~MASTAREA.2da~ ~XG0002 value~ UNLESS ~XG0002~ // Plaines Étincelantes // The Shining Plains //
	APPEND ~MASTAREA.2da~ ~XG0003 value~ UNLESS ~XG0003~ // Bois de Turlang // Turlan Forest //
	APPEND ~MASTAREA.2da~ ~XG0004 value~ UNLESS ~XG0004~ // Mines de Feu vagabondes // Wandering Fire Mines //
	APPEND ~MASTAREA.2da~ ~XG0007 value~ UNLESS ~XG0007~ // Le Fort de la Sorcière // Witch's Strength //
	APPEND ~MASTAREA.2da~ ~XG0801 value~ UNLESS ~XG0801~ // Camp Hrothgar // Hrothgar Camp //
	APPEND ~MASTAREA.2da~ ~XG0009 value~ UNLESS ~XG0009~ // Maison des Morts-vivants // Undead Housing //
	APPEND ~MASTAREA.2da~ ~XG0034 value~ UNLESS ~XG0034~ // Le Conseil des Mages  // Council of Mages //
	APPEND ~MASTAREA.2da~ ~XG0012 value~ UNLESS ~XG0012~ // Château des Collines Oubliées // Castle Forgotten Hills //
	APPEND ~MASTAREA.2da~ ~XG0014 value~ UNLESS ~XG0014~ // Île du pirate (Mer des étoiles déchues) //  Pirate island //
	APPEND ~MASTAREA.2da~ ~XG0015 value~ UNLESS ~XG0015~ // Crevasse //
	APPEND ~MASTAREA.2da~ ~XG0016 value~ UNLESS ~XG0016~ // Passe du Géant // Pass //
	APPEND ~MASTAREA.2da~ ~XG0017 value~ UNLESS ~XG0017~ // Tour de Gradak // Tower of Gradak //
	APPEND ~MASTAREA.2da~ ~XG0018 value~ UNLESS ~XG0018~ // Camp Secret de Gradak
	APPEND ~MASTAREA.2da~ ~XG0019 value~ UNLESS ~XG0019~ // Navire de Gradak // Ship of Gradak //

ACTION_IF NOT GAME_IS ~bgt eet~ BEGIN

	APPEND ~MASTAREA.2da~ ~XG0020 value~ UNLESS ~XG0020~ // Porte de Baldur  // Baldur's Gate  //

END

	APPEND ~MASTAREA.2da~ ~XG0025 value~ UNLESS ~XG0025~ // Quais de Targos // Docks of Targos //
	APPEND ~MASTAREA.2da~ ~XG0024 value~ UNLESS ~XG0024~ // Targos // Targos Town //
	APPEND ~MASTAREA.2da~ ~XG0026 value~ UNLESS ~XG0026~ // Haute-Forêt // The High Forest //
	APPEND ~MASTAREA.2da~ ~XG0064 value~ UNLESS ~XG0064~ // Eauprofonde // Waterdeep //
	APPEND ~MASTAREA.2da~ ~XG0028 value~ UNLESS ~XG0028~ // Château des Montagnes Floconeigeuses // Fort on Snowflake mountains //
	APPEND ~MASTAREA.2da~ ~XG0319 value~ UNLESS ~XG0319~ // Village Abandonné // Abandoned Village //
	APPEND ~MASTAREA.2da~ ~XG0029 value~ UNLESS ~XG0029~ // Cite des Prêtres (Pres de Berdusk) // Priests City // Har Al-Dur //
	APPEND ~MASTAREA.2da~ ~XG0033 value~ UNLESS ~XG0033~ // Village (près de Teziir) // Village //
	APPEND ~MASTAREA.2da~ ~XG0039 value~ UNLESS ~XG0039~ // Îles Moonshae // Moonshae Isles //
	APPEND ~MASTAREA.2da~ ~XG0040 value~ UNLESS ~XG0040~ // Îles Moonshae // Moonshae Isles //
	APPEND ~MASTAREA.2da~ ~XG0068 value~ UNLESS ~XG0068~ // Quartier des Affaires // Business district //
	APPEND ~MASTAREA.2da~ ~XG0041 value~ UNLESS ~XG0041~ // Îles Moonshae // Moonshae Isles //
	APPEND ~MASTAREA.2da~ ~XG0046 value~ UNLESS ~XG0046~ // Temple oublie // Forgotten Temple //
	APPEND ~MASTAREA.2da~ ~XG0047 value~ UNLESS ~XG0047~ // Port de l'Est (Icewind Dale) // East Harbor //
	APPEND ~MASTAREA.2da~ ~XG0057 value~ UNLESS ~XG0057~ // Port de Padhiver // Neverwinter harbor
	APPEND ~MASTAREA.2da~ ~XG0062 value~ UNLESS ~XG0062~ // Padhiver // Neverwinter
	APPEND ~MASTAREA.2da~ ~XG0050 value~ UNLESS ~XG0050~ // Montagnes (sous le festival) // Mountains //
	APPEND ~MASTAREA.2da~ ~XG0052 value~ UNLESS ~XG0052~ // Forteresse Glacée // Ice Castle //
	APPEND ~MASTAREA.2da~ ~XG0054 value~ UNLESS ~XG0054~ // Refuge (de Gradak) // Shelter //
	APPEND ~MASTAREA.2da~ ~XG0055 value~ UNLESS ~XG0055~ // Tour de Gradak (bis) // Tower of Gradak //
	APPEND ~MASTAREA.2da~ ~XG0061 value~ UNLESS ~XG0061~ // Forêt (vers les Montagnes du Couchant) // Forest //
	APPEND ~MASTAREA.2da~ ~XG0065 value~ UNLESS ~XG0065~ // Village (près de Soubar) // Village //
	APPEND ~MASTAREA.2da~ ~XG0066 value~ UNLESS ~XG0066~ // Col de la Forêt // Pass //
	APPEND ~MASTAREA.2da~ ~XG0067 value~ UNLESS ~XG0067~ // Vallée de L'Epine Dorsale // Valley of Icewind Dale //
	APPEND ~MASTAREA.2da~ ~XG0069 value~ UNLESS ~XG0069~ // Chasse aux Trolls // Hunting Trolls //
	APPEND ~MASTAREA.2da~ ~XG0053 value~ UNLESS ~XG0053~ // Le Culte // Cult //
	APPEND ~MASTAREA.2da~ ~XG0056 value~ UNLESS ~XG0056~ // Vallée // Valley //
	APPEND ~MASTAREA.2da~ ~XG0059 value~ UNLESS ~XG0059~ // Village (Floconeigeuse) // Village //
	APPEND ~MASTAREA.2da~ ~XG0060 value~ UNLESS ~XG0060~ // Montagnes (Floconeigeuse) // Mountains //
	APPEND ~MASTAREA.2da~ ~XG0070 value~ UNLESS ~XG0070~ // Ferme (près du Gué de la Dague) // Farm //
	APPEND ~MASTAREA.2da~ ~XG0072 value~ UNLESS ~XG0072~ // Désert Calim (près de Memnon) // Calim Desert //
	APPEND ~MASTAREA.2da~ ~XG0073 value~ UNLESS ~XG0073~ // Désert Calim  (près de Darromar)// Calim Desert //
	APPEND ~MASTAREA.2da~ ~XG0075 value~ UNLESS ~XG0075~ // Arène // Arena //
	APPEND ~MASTAREA.2da~ ~XG1319 value~ UNLESS ~XG1319~ // Village Abandonné (bis) // Abandoned Village //
	APPEND ~MASTAREA.2da~ ~XG0076 value~ UNLESS ~XG0076~ // Forêt de Tethyr // Forest of Tehyr //
	APPEND ~MASTAREA.2da~ ~XG0077 value~ UNLESS ~XG0077~ // Forêt de Tethyr // Forest of Tehyr //
	APPEND ~MASTAREA.2da~ ~XG0078 value~ UNLESS ~XG0078~ // Château-Tethyr // Castle of Tehyr //
	APPEND ~MASTAREA.2da~ ~XG0058 value~ UNLESS ~XG0058~ // Vallée de L'Epine Dorsale // Valley of Icewind Dale //
	APPEND ~MASTAREA.2da~ ~XG0079 value~ UNLESS ~XG0079~ // Ferme (près d'Esmeltaran) // Farm //
	APPEND ~MASTAREA.2da~ ~XG4001 value~ UNLESS ~XG4001~ // Îles Moonshae // Moonshae Isles //
	APPEND ~MASTAREA.2da~ ~XG0081 value~ UNLESS ~XG0081~ // Village du Couchant (Torm) // Twilight Mountains //
	APPEND ~MASTAREA.2da~ ~XG1081 value~ UNLESS ~XG1081~ // Village du Couchant (Torm monastère) // Twilight Mountains //
	APPEND ~MASTAREA.2da~ ~XG0082 value~ UNLESS ~XG0082~ // Montagnes du Couchant // Twilight Mountains //
	APPEND ~MASTAREA.2da~ ~XG0083 value~ UNLESS ~XG0083~ // Montagnes du Couchant // Twilight Mountains //
	APPEND ~MASTAREA.2da~ ~XG0133 value~ UNLESS ~XG0133~ // Village (près de Teziir) (bis) // Village //
	APPEND ~MASTAREA.2da~ ~XG8100 value~ UNLESS ~XG8100~ // Village du Couchant (Cyric) // Twilight Mountains //
	APPEND ~MASTAREA.2da~ ~XG8101 value~ UNLESS ~XG8101~ // Village du Couchant (Cyric monastère) // Twilight Mountains //
	APPEND ~MASTAREA.2da~ ~XG8200 value~ UNLESS ~XG8200~ // Montagnes du Couchant (bis) // Twilight Mountains //
	APPEND ~MASTAREA.2da~ ~XG8300 value~ UNLESS ~XG8300~ // Montagnes du Couchant (bis) // Twilight Mountains //
	APPEND ~MASTAREA.2da~ ~XGKAR2 value~ UNLESS ~XGKAR2~ // Caravane // Caravan //
	APPEND ~MASTAREA.2da~ ~XG0681 value~ UNLESS ~XG0681~ // Monastère des admirateur de Torm // Torm admirers Monastery //
	APPEND ~MASTAREA.2da~ ~XG8500 value~ UNLESS ~XG8500~ // Monastère des serviteurs de Cyric // Cyric admirers Monastery //
	APPEND ~MASTAREA.2da~ ~XG0084 value~ UNLESS ~XG0084~ // La Plaine Gelée // The Frozen Plain //
	APPEND ~MASTAREA.2da~ ~XG0A80 value~ UNLESS ~XG0A80~ // Siluvanede (bis)
	APPEND ~MASTAREA.2da~ ~XG0080 value~ UNLESS ~XG0080~ // Siluvanede
	APPEND ~MASTAREA.2da~ ~XG0780 value~ UNLESS ~XG0780~ // Camp Eilistraee
	APPEND ~MASTAREA.2da~ ~XG0680 value~ UNLESS ~XG0680~ // Forêt de Siluvanede // Forest //


/*
////////////////////////////////////////////////////////////////////
//BG2 BG2EE

	ACTION_IF NOT GAME_IS ~bgt eet~ AND FILE_EXISTS ~Worldmap/map_mods_areas.tbl~ THEN BEGIN

    COPY ~Worldmap/map_mods_areas.tbl~		~Worldmap~
     APPEND_FILE ~Paladins-of-Faerun/Worldmap/areas.tbl~

    COPY ~Worldmap/map_mods_links.tbl~		~Worldmap~
     APPEND_FILE ~Paladins-of-Faerun/Worldmap/links.tbl~

    COPY ~Worldmap/map_mods_trans.tra~		~Worldmap~
     APPEND_FILE_EVALUATE ~weidu_external/Paladins-of-Faerun/Languages/autotra/%LANGUAGE%/worldmap.tra~

  END ELSE ACTION_IF NOT GAME_IS ~bgt eet~ AND NOT FILE_EXISTS ~Worldmap/map_mods_areas.tbl~ BEGIN

	MKDIR ~Worldmap~

	COPY ~Paladins-of-Faerun/Worldmap/areas.tbl~			~Worldmap/map_mods_areas.tbl~

	COPY ~Paladins-of-Faerun/Worldmap/links.tbl~			~Worldmap/map_mods_links.tbl~

	COPY ~weidu_external/Paladins-of-Faerun/Languages/autotra/%LANGUAGE%/worldmap.tra~	~Worldmap/map_mods_trans.tra~

  END
END

////////////////////////////////////////////////////////////////////
//BGT EET

	ACTION_IF GAME_IS ~bgt eet~ AND FILE_EXISTS ~Worldmap/map_mods_areas.tbl~ THEN BEGIN

    COPY ~Worldmap/map_mods_areas.tbl~		~Worldmap~
     APPEND_FILE ~Paladins-of-Faerun/Worldmap/areas.tbl~

    COPY ~Worldmap/map_mods_links.tbl~		~Worldmap~
     APPEND_FILE ~weidu_external/Paladins-of-Faerun/Worldmap/links.tbl~

    COPY ~Worldmap/map_mods_trans.tra~		~Worldmap~
     APPEND_FILE_EVALUATE ~weidu_external/Paladins-of-Faerun/Languages/autotra/%LANGUAGE%/worldmap.tra~

  END ELSE ACTION_IF GAME_IS ~bgt eet~ AND NOT FILE_EXISTS ~Worldmap/map_mods_areas.tbl~ BEGIN

	MKDIR ~Worldmap~

	COPY ~Paladins-of-Faerun/Worldmap/areas.tbl~							~Worldmap/map_mods_areas.tbl~

	COPY ~weidu_external/Paladins-of-Faerun/Worldmap/links.tbl~			~Worldmap/map_mods_links.tbl~

	COPY ~weidu_external/Paladins-of-Faerun/Languages/autotra/%LANGUAGE%/worldmap.tra~	~Worldmap/map_mods_trans.tra~

  END
END
*/