
//////////////////////////////////
// Setup  Items
//////////////////////////////////

MKDIR ~weidu_external/Paladins-of-Faerun/Items~

//  BAM For Items
ACTION_BASH_FOR ~Paladins-of-Faerun/Items~ ~^.+$~ BEGIN

PRINT ~         ~
PRINT ~START BAM_NAMES_ON_ITM~
PRINT ~         ~

  COPY ~%BASH_FOR_FILESPEC%~ ~weidu_external/%BASH_FOR_FILESPEC%~
    LPM UPDATE_POF_BAM_NAMES_ON_ITM
	// Bam-macros.tpa
PRINT ~         ~
PRINT ~END BAM_NAMES_ON_ITM~
PRINT ~         ~

END


ACTION_BASH_FOR ~weidu_external/Paladins-of-Faerun/Items~ ~^.+$~ BEGIN

PRINT ~         ~
PRINT ~START BAM_NAMES_ON_ITM~
PRINT ~         ~

  COPY ~%BASH_FOR_FILESPEC%~ ~%BASH_FOR_FILESPEC%~
    LPM UPDATE_POF_BAM_NAMES_ON_ITM_ABYLITY
	// Bam-macros.tpa	
PRINT ~         ~
PRINT ~END BAM_NAMES_ON_ITM~
PRINT ~         ~

END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGcd.ITM~			~override/XGcd.ITM~ // Addition CDMOD.ITM - XGcd.ITM
  SAY NAME1 @1060
  SAY NAME2 @1061
  SAY DESC @1062
  SAY UNIDENTIFIED_DESC @1063

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAM1.ITM~			~override/XGAM1.ITM~
  SAY NAME1 @433
  SAY NAME2 @433
  SAY DESC #22096
  SAY UNIDENTIFIED_DESC #22096

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAM2.ITM~			~override/XGAM2.ITM~
  SAY NAME1 @434
  SAY NAME2 @434
  SAY DESC #22096
  SAY UNIDENTIFIED_DESC #22096

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAM3.ITM~			~override/XGAM3.ITM~
  SAY NAME1 @435
  SAY NAME2 @435
  SAY DESC #22096
  SAY UNIDENTIFIED_DESC #22096

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAM4.ITM~			~override/XGAM4.ITM~
  SAY NAME1 @436
  SAY NAME2 @436
  SAY DESC #22096
  SAY UNIDENTIFIED_DESC #22096

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAM5.ITM~			~override/XGAM5.ITM~
  SAY NAME1 @437
  SAY NAME2 @437
  SAY DESC #22096
  SAY UNIDENTIFIED_DESC #22096

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAM.ITM~			~override/XGAM.ITM~
  SAY NAME1 @438
  SAY NAME2 @438
  SAY DESC #22096
  SAY UNIDENTIFIED_DESC #22096

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAMUL1.ITM~			~override/XGAMUL1.ITM~
  SAY NAME2 @439
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@440" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAMUL2.ITM~			~override/XGAMUL2.ITM~
  SAY NAME2 @441
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@442" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAMUL3.ITM~			~override/XGAMUL3.ITM~
  SAY NAME2 @443
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@444" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAMUL4.ITM~			~override/XGAMUL4.ITM~
  SAY NAME2 @445
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@446" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGartk1.ITM~			~override/XGartk1.ITM~
  SAY NAME1 @447
  SAY NAME2 @447
  SAY UNIDENTIFIED_DESC @448
  SAY DESC @448

COPY ~weidu_external/Paladins-of-Faerun/Items/XGARTK.ITM~			~override/XGARTK.ITM~
  SAY NAME1 @447
  SAY NAME2 @447
  SAY UNIDENTIFIED_DESC @448
  SAY DESC @448

COPY ~weidu_external/Paladins-of-Faerun/Items/XGART.ITM~			~override/XGART.ITM~
  SAY NAME1 @447
  SAY NAME2 @447
  SAY UNIDENTIFIED_DESC @449
  SAY DESC @449

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAXE01.ITM~			~override/XGAXE01.ITM~
  SAY NAME2 @450
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@451" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAXE02.ITM~			~override/XGAXE02.ITM~
  SAY NAME2 @452
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@453" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAXE03.ITM~			~override/XGAXE03.ITM~
  SAY NAME2 @454
  SAY DESC @455

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAXE04.ITM~			~override/XGAXE04.ITM~
  SAY NAME2 @456
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@457" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAXE05.ITM~			~override/XGAXE05.ITM~
  SAY NAME2 @458
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@459" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAXE06.ITM~			~override/XGAXE06.ITM~
  SAY NAME2 @460
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@461" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGAXE07.ITM~			~override/XGAXE07.ITM~
  SAY NAME2 @462
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@463" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBELT1.ITM~			~override/XGBELT1.ITM~
  SAY NAME2 @464
  SAY DESC @465

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBELT2.ITM~			~override/XGBELT2.ITM~
  SAY NAME2 @466
  SAY DESC @467

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBELT3.ITM~			~override/XGBELT3.ITM~
  SAY NAME2 @468
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@469" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBGSD.ITM~			~override/XGBGSD.ITM~
  SAY NAME1 @470
  SAY NAME2 @470
  SAY UNIDENTIFIED_DESC @471
  SAY DESC @471

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBHARF.ITM~			~override/XGBHARF.ITM~
  SAY NAME1 @472

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBOOKP.ITM~			~override/XGBOOKP.ITM~ // Addition (description)
  SAY NAME1 @2000
  SAY NAME2 @2003
  SAY DESC @2001

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBOOT1.ITM~			~override/XGBOOT1.ITM~
  SAY NAME2 @473
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@474" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBOOT2.ITM~			~override/XGBOOT2.ITM~
  SAY NAME2 @475
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@476" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBOOT3.ITM~			~override/XGBOOT3.ITM~
  SAY NAME2 @477 
  SAY DESC @478 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBOOT4.ITM~			~override/XGBOOT4.ITM~
  SAY NAME2 @479 
  SAY DESC @480 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBRAC1.ITM~			~override/XGBRAC1.ITM~
  SAY NAME2 @481 
  SAY DESC @482 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBRAC2.ITM~			~override/XGBRAC2.ITM~
  SAY NAME2 @483 
  SAY DESC @484 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBRAC3.ITM~			~override/XGBRAC3.ITM~
  SAY NAME2 @485
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@486" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBRAC4.ITM~			~override/XGBRAC4.ITM~
  SAY NAME2 @487 
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@488" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBSWO1.ITM~			~override/XGBSWO1.ITM~
  SAY NAME1 @489
  SAY NAME2 @489
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@490" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@490" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBSWO2.ITM~			~override/XGBSWO2.ITM~
  SAY NAME1 @489
  SAY NAME2 @491
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@490" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@492" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBSWO3.ITM~			~override/XGBSWO3.ITM~
  SAY NAME1 @489
  SAY NAME2 @493
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@490" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@494" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBSWO4.ITM~			~override/XGBSWO4.ITM~
  SAY NAME1 @489
  SAY NAME2 @495
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@490" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@496" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBSWO5.ITM~			~override/XGBSWO5.ITM~
  SAY NAME1 @489
  SAY NAME2 @497
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@490" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@498" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBSWO6.ITM~			~override/XGBSWO6.ITM~
  SAY NAME1 @489
  SAY NAME2 @499
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@490" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@500" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBSWO7.ITM~			~override/XGBSWO7.ITM~
  SAY NAME1 @489
  SAY NAME2 @501
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@490" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@502" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBSWO8.ITM~			~override/XGBSWO8.ITM~
  SAY NAME1 @489
  SAY NAME2 @503
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@490" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@504" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGBSWO9.ITM~			~override/XGBSWO9.ITM~
  SAY NAME1 @489
  SAY NAME2 @505
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@490" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@506" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGCBOW1.ITM~			~override/XGCBOW1.ITM~
  SAY NAME2 @507
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@508" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGCBOW2.ITM~			~override/XGCBOW2.ITM~
  SAY NAME2 @509
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@510" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGCBOW3.ITM~			~override/XGCBOW3.ITM~
  SAY NAME2 @511
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@512" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGCLUB1.ITM~			~override/XGCLUB1.ITM~
  SAY NAME2 @513
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@514" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGCLUB2.ITM~			~override/XGCLUB2.ITM~
  SAY NAME2 @515
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@516" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGCLUB3.ITM~			~override/XGCLUB3.ITM~
  SAY NAME2 @517
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@518" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFLAI1.ITM~			~override/XGFLAI1.ITM~
  SAY NAME2 @519
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@520" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFLAI2.ITM~			~override/XGFLAI2.ITM~
  SAY NAME2 @521
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@522" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFLAI3.ITM~			~override/XGFLAI3.ITM~
  SAY NAME2 @523 
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@524" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGCLCK1.ITM~			~override/XGCLCK1.ITM~
  SAY NAME1 @525
  SAY NAME2 @525
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@526" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@526" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGCMA01.ITM~			~override/XGCMA01.ITM~
  SAY NAME2 @527
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@528" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGCMA01.EFF~			~override/XGCMA01.EFF~

COPY ~weidu_external/Paladins-of-Faerun/Items/XGCMA02.ITM~			~override/XGCMA02.ITM~
  SAY NAME2 @529
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@53" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGCMA03.ITM~			~override/XGCMA03.ITM~
  SAY NAME2 @531
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@532" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGDBOOK.ITM~			~override/XGDBOOK.ITM~
  SAY NAME1 @533 
  SAY NAME2 @533 
  SAY UNIDENTIFIED_DESC @533 
  SAY DESC @533 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGDEVH.ITM~			~override/XGDEVH.ITM~
  SAY NAME1 @534 
  SAY NAME2 @534 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGDHEA1.ITM~			~override/XGDHEA1.ITM~
  SAY NAME1 @535 
  SAY NAME2 @535 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGDHEAR.ITM~			~override/XGDHEAR.ITM~
  SAY NAME1 @535 
  SAY NAME2 @535 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGDOAX.ITM~			~override/XGDOAX.ITM~
  SAY NAME2 @536
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@537" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGdram.ITM~			~override/XGdram.ITM~
  SAY NAME2 @538 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGERKEY.ITM~			~override/XGERKEY.ITM~
  SAY NAME1 @539 
  SAY NAME2 @539 
  SAY UNIDENTIFIED_DESC @539 
  SAY DESC @539 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGESD.ITM~			~override/XGESD.ITM~
  SAY NAME1 @540 
  SAY NAME2 @540 
  SAY UNIDENTIFIED_DESC @541 
  SAY DESC @541 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGesh.ITM~			~override/XGesh.ITM~
  SAY UNIDENTIFIED_DESC @542
  SAY DESC @542

COPY ~weidu_external/Paladins-of-Faerun/Items/XGESK.ITM~			~override/XGESK.ITM~
  SAY NAME1 @543
  SAY NAME2 @543 
  
COPY ~weidu_external/Paladins-of-Faerun/Items/XGFA11.ITM~			~override/XGFA11.ITM~
  SAY NAME1 #12004
  SAY NAME2 #12004
  SAY UNIDENTIFIED_DESC #6889
  SAY DESC #6889
  
COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALH1.ITM~			~override/XGFALH1.ITM~
  SAY NAME1 @544
  SAY NAME2 @544
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@545" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@545" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALH2.ITM~			~override/XGFALH2.ITM~
  SAY NAME1 @544
  SAY NAME2 @546
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@545" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@547" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALH3.ITM~			~override/XGFALH3.ITM~
  SAY NAME1 @544 
  SAY NAME2 @548
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@545" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@549" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALH4.ITM~			~override/XGFALH4.ITM~
  SAY NAME1 @544
  SAY NAME2 @550
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@545" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@551" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALH5.ITM~			~override/XGFALH5.ITM~
  SAY NAME1 @544
  SAY NAME2 @552
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@545" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@553" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALH6.ITM~			~override/XGFALH6.ITM~
  SAY NAME1 @544 
  SAY NAME2 @554
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@545" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@555" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALX1.ITM~			~override/XGFALX1.ITM~
  SAY NAME1 @556
  SAY NAME2 @556
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@557" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@557" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALX2.ITM~			~override/XGFALX2.ITM~
  SAY NAME1 @556
  SAY NAME2 @558
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@557" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@559" END 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALX3.ITM~			~override/XGFALX3.ITM~
  SAY NAME1 @556
  SAY NAME2 @560
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@557" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@561" END 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALX4.ITM~			~override/XGFALX4.ITM~
  SAY NAME1 @556
  SAY NAME2 @562
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@557" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@563" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALX5.ITM~			~override/XGFALX5.ITM~
  SAY NAME1 @556
  SAY NAME2 @564
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@557" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@565" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALX6.ITM~			~override/XGFALX6.ITM~
  SAY NAME1 @556
  SAY NAME2 @566
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@557" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@567" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFALX7.ITM~			~override/XGFALX7.ITM~
  SAY NAME1 @556
  SAY NAME2 @568
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@557" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@569" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGFAR.ITM~			~override/XGFAR.ITM~
  SAY NAME2 @570
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@571" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGD1.ITM~			~override/XGGD1.ITM~
  SAY NAME1 @572 
  SAY NAME2 @572 
  SAY UNIDENTIFIED_DESC @572 
  SAY DESC @572 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGD2.ITM~			~override/XGGD2.ITM~
  SAY NAME1 @572 
  SAY NAME2 @572 
  SAY UNIDENTIFIED_DESC @572 
  SAY DESC @572 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGD3.ITM~			~override/XGGD3.ITM~
  SAY NAME1 @572 
  SAY NAME2 @572 
  SAY UNIDENTIFIED_DESC @572 
  SAY DESC @572 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLA.ITM~			~override/XGGLA.ITM~
  SAY NAME2 @573
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@574" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAVE.ITM~			~override/XGGLAVE.ITM~
  SAY NAME1 @575
  SAY NAME2 @575
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@576" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV1.ITM~			~override/XGGLAV1.ITM~
  SAY NAME1 @575
  SAY NAME2 @577
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@578" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@579" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV2.ITM~			~override/XGGLAV2.ITM~
  SAY NAME1 @575
  SAY NAME2 @580
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@578" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@581" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV3.ITM~			~override/XGGLAV3.ITM~
  SAY NAME1 @575
  SAY NAME2 @582
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@578" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@583" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV4.ITM~			~override/XGGLAV4.ITM~
  SAY NAME1 @575
  SAY NAME2 @584
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@578" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@585" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV5.ITM~			~override/XGGLAV5.ITM~
  SAY NAME1 @575
  SAY NAME2 @586
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@578" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@587" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV7.ITM~			~override/XGGLAV7.ITM~
  SAY NAME1 @575
  SAY NAME2 @588
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@589" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV8.ITM~			~override/XGGLAV8.ITM~
  SAY NAME1 @575
  SAY NAME2 @590
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@591" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV9.ITM~			~override/XGGLAV9.ITM~
  SAY NAME1 @575
  SAY NAME2 @592
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@593" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLAV10.ITM~			~override/XGLAV10.ITM~
  SAY NAME1 @575
  SAY NAME2 @594
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@595" END
  
//

//+2
COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV17.ITM~			~override/XGGLAV17.ITM~
  SAY NAME1 @575
  SAY NAME2 @4000
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4001" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV18.ITM~			~override/XGGLAV18.ITM~
  SAY NAME1 @575
  SAY NAME2 @4002
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4003" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV19.ITM~			~override/XGGLAV19.ITM~
  SAY NAME1 @575
  SAY NAME2 @4004
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4005" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLAV11.ITM~			~override/XGLAV11.ITM~
  SAY NAME1 @575
  SAY NAME2 @4006
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4007" END

//+3
COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV27.ITM~			~override/XGGLAV27.ITM~
  SAY NAME1 @575
  SAY NAME2 @4008
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4009" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV28.ITM~			~override/XGGLAV28.ITM~
  SAY NAME1 @575
  SAY NAME2 @4010
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4011" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV29.ITM~			~override/XGGLAV29.ITM~
  SAY NAME1 @575
  SAY NAME2 @4012
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4013" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLAV21.ITM~			~override/XGLAV21.ITM~
  SAY NAME1 @575
  SAY NAME2 @4014
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4015" END
  

// +Spéciale
COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV30.ITM~			~override/XGGLAV30.ITM~
  SAY NAME1 @575
  SAY NAME2 @4016
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4017" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV31.ITM~			~override/XGGLAV31.ITM~
  SAY NAME1 @575
  SAY NAME2 @4018
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4019" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV32.ITM~			~override/XGGLAV32.ITM~
  SAY NAME1 @575
  SAY NAME2 @4020
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4021" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGGLAV40.ITM~			~override/XGGLAV40.ITM~
  SAY NAME1 @575
  SAY NAME2 @4022
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@576" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@4023" END

//

COPY ~weidu_external/Paladins-of-Faerun/Items/XGHAL01.ITM~			~override/XGHAL01.ITM~
  SAY NAME2 @596
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@597" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGHAL02.ITM~			~override/XGHAL02.ITM~
  SAY NAME2 @598
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@599" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGHAL03.ITM~			~override/XGHAL03.ITM~
  SAY NAME2 @600
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@601" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGHAM3.ITM~			~override/XGHAM3.ITM~
  SAY NAME2 @602
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@603" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGHAMM1.ITM~			~override/XGHAMM1.ITM~
  SAY NAME2 @604
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@605" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGHAMM2.ITM~			~override/XGHAMM2.ITM~
  SAY NAME2 @606
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@607" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGHELM1.ITM~			~override/XGHELM1.ITM~
  SAY NAME2 @608
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@609" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGHELM2.ITM~			~override/XGHELM2.ITM~
  SAY NAME2 @610
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@611" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGHELM3.ITM~			~override/XGHELM3.ITM~
  SAY NAME2 @612
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@613" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGHELM4.ITM~			~override/XGHELM4.ITM~
  SAY NAME2 @614
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@615" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGhq.ITM~			~override/XGhq.ITM~
  SAY NAME1 @616 
  SAY NAME2 @616 
  SAY UNIDENTIFIED_DESC @617 
  SAY DESC @617 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGhsr.ITM~			~override/XGhsr.ITM~
  SAY NAME1 @618 
  SAY NAME2 @618 
  SAY UNIDENTIFIED_DESC @618 
  SAY DESC @618 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGIK01.ITM~			~override/XGIK01.ITM~
  SAY NAME1 @619
  SAY NAME2 @619
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@620" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@620" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGIK02.ITM~			~override/XGIK02.ITM~
  SAY NAME1 @619
  SAY NAME2 @621
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@620" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@622" END 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGIK03.ITM~			~override/XGIK03.ITM~
  SAY NAME1 @619
  SAY NAME2 @623
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@620" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@624" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGIK04.ITM~			~override/XGIK04.ITM~
  SAY NAME1 @619
  SAY NAME2 @625
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@620" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@626" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGIK05.ITM~			~override/XGIK05.ITM~
  SAY NAME1 @619
  SAY NAME2 @627
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@620" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@628" END 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGIK06.ITM~			~override/XGIK06.ITM~
  SAY NAME1 @619
  SAY NAME2 @629
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@620" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@630" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGIK07.ITM~			~override/XGIK07.ITM~
  SAY NAME1 @619
  SAY NAME2 @631
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@620" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@632" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGiqq.ITM~			~override/XGiqq.ITM~
  SAY NAME1 @447
  SAY NAME2 @447
  SAY UNIDENTIFIED_DESC @447
  SAY DESC @447

COPY ~weidu_external/Paladins-of-Faerun/Items/XGKAT01.ITM~			~override/XGKAT01.ITM~
  SAY NAME2 @633
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@634" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGKAT01.EFF~			~override/XGKAT01.EFF~

COPY ~weidu_external/Paladins-of-Faerun/Items/XGKAT02.ITM~			~override/XGKAT02.ITM~
  SAY NAME2 @635
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@636" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGKAT03.ITM~			~override/XGKAT03.ITM~
  SAY NAME2 @637
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@638" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGKAT04.ITM~			~override/XGKAT04.ITM~
  SAY NAME2 @639
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@640" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGKEV1.ITM~			~override/XGKEV1.ITM~
  SAY NAME1 @641
  SAY NAME2 @641
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@642" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@642" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGKEV2.ITM~			~override/XGKEV2.ITM~
  SAY NAME1 @643
  SAY NAME2 @643
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@644" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@644" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGKIIT.ITM~			~override/XGKIIT.ITM~
  SAY NAME1 @645 
  SAY NAME2 @645
  SAY UNIDENTIFIED_DESC @646 
  SAY DESC @646 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGku.ITM~			~override/XGku.ITM~

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLAN02.ITM~			~override/XGLAN02.ITM~
  SAY NAME2 @647
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@648" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLAN03.ITM~			~override/XGLAN03.ITM~
  SAY NAME2 @649
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@650" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLEAT1.ITM~			~override/XGLEAT1.ITM~
  SAY NAME1 @651
  SAY NAME2 @651
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@652" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@652" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGleta.ITM~			~override/XGleta.ITM~

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLETER.ITM~			~override/XGLETER.ITM~
  SAY NAME1 @653
  SAY NAME2 @653
  SAY UNIDENTIFIED_DESC @654 
  SAY DESC @654 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGleths.ITM~			~override/XGleths.ITM~
  SAY NAME1 @655 
  SAY NAME2 @655 
  SAY UNIDENTIFIED_DESC @656 
  SAY DESC @656 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLETL.ITM~			~override/XGLETL.ITM~
  SAY NAME1 @655 
  SAY NAME2 @655 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLETT1.ITM~			~override/XGLETT1.ITM~
  SAY UNIDENTIFIED_DESC @657 
  SAY DESC @657 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLETT2.ITM~			~override/XGLETT2.ITM~
  SAY UNIDENTIFIED_DESC @658 
  SAY DESC @658 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLETT.ITM~			~override/XGLETT.ITM~
  SAY NAME1 @659 
  SAY NAME2 @659 
  SAY UNIDENTIFIED_DESC @660 
  SAY DESC @660 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLETW.ITM~			~override/XGLETW.ITM~
  SAY NAME1 @661 
  SAY NAME2 @661 
  SAY UNIDENTIFIED_DESC @662 
  SAY DESC @662 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGls.ITM~			~override/XGls.ITM~
  SAY UNIDENTIFIED_DESC @658 
  SAY DESC @658 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLUSWQ.ITM~			~override/XGLUSWQ.ITM~
  SAY NAME1 @663 
  SAY NAME2 @663 
  SAY UNIDENTIFIED_DESC @664 
  SAY DESC @664 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGLWLET.ITM~			~override/XGLWLET.ITM~
  SAY NAME1 @665 
  SAY NAME2 @665 
  SAY DESC @666 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMAGG.ITM~			~override/XGMAGG.ITM~
  SAY NAME1 @667 
  SAY NAME2 @667 
  SAY UNIDENTIFIED_DESC @667 
  SAY DESC @667 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMAP.ITM~			~override/XGMAP.ITM~
  SAY NAME1 @668 
  SAY NAME2 @668 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMAR1.ITM~			~override/XGMAR1.ITM~
  SAY NAME2 @669 
  SAY DESC @670 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMAR.ITM~			~override/XGMAR.ITM~
  SAY NAME2 @671 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMB.ITM~			~override/XGMB.ITM~

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMBOOK.ITM~			~override/XGMBOOK.ITM~
  SAY NAME1 @672 
  SAY NAME2 @672 
  SAY UNIDENTIFIED_DESC @673 
  SAY DESC @673 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMBOW1.ITM~			~override/XGMBOW1.ITM~
  SAY NAME2 @674
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@675" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMBOW2.ITM~			~override/XGMBOW2.ITM~
  SAY NAME2 @676
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@677" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMBOW3.ITM~			~override/XGMBOW3.ITM~
  SAY NAME2 @678
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@679" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMCA.ITM~			~override/XGMCA.ITM~
  SAY NAME1 #6337
  SAY NAME2 #6337
  SAY UNIDENTIFIED_DESC #6709
  SAY DESC @681 // Not accurate (probably not implemented) 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMISC.ITM~			~override/XGMISC.ITM~
  SAY NAME1 @682 
  SAY NAME2 @682 
  SAY UNIDENTIFIED_DESC @683 
  SAY DESC @683

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMIT.ITM~			~override/XGMIT.ITM~
  SAY NAME2 @684 
  SAY DESC @685 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMNEK1.ITM~			~override/XGMNEK1.ITM~
  SAY NAME1 @686 
  SAY NAME2 @686 
  SAY UNIDENTIFIED_DESC @687 
  SAY DESC @687 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMOONH.ITM~			~override/XGMOONH.ITM~
  SAY NAME1 @688 
  SAY NAME2 @688 
  SAY UNIDENTIFIED_DESC @689 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMOONS.ITM~			~override/XGMOONS.ITM~
  SAY NAME1 #6860
  SAY NAME2 @674
  SAY UNIDENTIFIED_DESC #6862 
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@690" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMPLAT.ITM~			~override/XGMPLAT.ITM~ // Not implemented / Wrong description reference (an armor not a Crossbow of Discharge)
  SAY NAME2 @511 
  SAY DESC @512 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMRBO.ITM~			~override/XGMRBO.ITM~
  SAY NAME1 @691
  SAY NAME2 @691

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMS01.ITM~			~override/XGMS01.ITM~
  SAY NAME2 @692
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@693" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMS02.ITM~			~override/XGMS02.ITM~
  SAY NAME2 @694
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@695" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMS03.ITM~			~override/XGMS03.ITM~
  SAY NAME2 @696
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@697" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSLIN1.ITM~			~override/XGSLIN1.ITM~
  SAY NAME2 @698 
  SAY DESC @699 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSLIN2.ITM~			~override/XGSLIN2.ITM~
  SAY NAME2 @700 
  SAY DESC @701 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSLIN3.ITM~			~override/XGSLIN3.ITM~
  SAY NAME2 @702 
  SAY DESC @703 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGmsq.ITM~			~override/XGmsq.ITM~
  SAY NAME1 @704 
  SAY NAME2 @704 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSTA1.ITM~			~override/XGSTA1.ITM~
  SAY NAME2 @705
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@706" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSTA2.ITM~			~override/XGSTA2.ITM~
  SAY NAME2 @707
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@708" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSTA3.ITM~			~override/XGSTA3.ITM~
  SAY NAME2 @709
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@710" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMTOK.ITM~			~override/XGMTOK.ITM~
  SAY NAME1 @711 
  SAY NAME2 @711 
  SAY UNIDENTIFIED_DESC @712 
  SAY DESC @712 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMWAND.ITM~			~override/XGMWAND.ITM~
  SAY NAME1 @713 
  SAY NAME2 @713 
  SAY UNIDENTIFIED_DESC @714 
  SAY DESC @714 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGMWD.ITM~			~override/XGMWD.ITM~
  SAY NAME1 @715 
  SAY NAME2 @715 
  SAY UNIDENTIFIED_DESC @715 
  SAY DESC @715 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGNINJ1.ITM~			~override/XGNINJ1.ITM~
  SAY NAME2 @716
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@717" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGNINJ2.ITM~			~override/XGNINJ2.ITM~
  SAY NAME2 @718
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@719" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGNINJ3.ITM~			~override/XGNINJ3.ITM~
  SAY NAME2 @720
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@721" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGNOMZ.ITM~			~override/XGNOMZ.ITM~
  SAY NAME2 @722
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@723" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGODSW.ITM~			~override/XGODSW.ITM~
  SAY NAME2 @724
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@725" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGODSW1.ITM~			~override/XGODSW1.ITM~
  SAY NAME2 @726
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@727" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGODSW2.ITM~			~override/XGODSW2.ITM~
  SAY NAME2 @728
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@729" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGODSW3.ITM~			~override/XGODSW3.ITM~
  SAY NAME2 @730
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@731" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPIK1.ITM~			~override/XGPIK1.ITM~
  SAY NAME1 @732
  SAY NAME2 @732
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@733" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@733" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPIK2.ITM~			~override/XGPIK2.ITM~
  SAY NAME1 @732
  SAY NAME2 @734
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@733" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@735" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPIK3.ITM~			~override/XGPIK3.ITM~
  SAY NAME1 @732
  SAY NAME2 @736
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@733" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@737" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPIK4.ITM~			~override/XGPIK4.ITM~
  SAY NAME1 @732
  SAY NAME2 @738
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@733" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@739" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPIK5.ITM~			~override/XGPIK5.ITM~
  SAY NAME1 @732
  SAY NAME2 @740
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@733" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@741" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPIK6.ITM~			~override/XGPIK6.ITM~
  SAY NAME1 @732
  SAY NAME2 @742
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@733" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@743" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPIK7.ITM~			~override/XGPIK7.ITM~
  SAY NAME1 @732
  SAY NAME2 @744
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@733" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@745" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGpk1.ITM~			~override/XGpk1.ITM~
  SAY NAME1 @746 
  SAY NAME2 @746 
  SAY UNIDENTIFIED_DESC @747 
  SAY DESC @747 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGpk2.ITM~			~override/XGpk2.ITM~
  SAY NAME1 @746 
  SAY NAME2 @746 
  SAY UNIDENTIFIED_DESC @748 
  SAY DESC @748 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGpk3.ITM~			~override/XGpk3.ITM~
  SAY NAME1 @746 
  SAY NAME2 @746 
  SAY UNIDENTIFIED_DESC @749 
  SAY DESC @749 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGpk4.ITM~			~override/XGpk4.ITM~
  SAY NAME1 @746 
  SAY NAME2 @746 
  SAY UNIDENTIFIED_DESC @750 
  SAY DESC @750 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGpk5.ITM~			~override/XGpk5.ITM~
  SAY NAME1 @746 
  SAY NAME2 @746 
  SAY UNIDENTIFIED_DESC @751 
  SAY DESC @751 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGpkc.ITM~			~override/XGpkc.ITM~
  SAY UNIDENTIFIED_DESC @752 
  SAY DESC @752 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLAT1.ITM~			~override/XGPLAT1.ITM~
  SAY NAME2 @753
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@754" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLA1M.ITM~			~override/XGPLA1M.ITM~
  SAY NAME1 @651
  SAY NAME2 @651
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@755" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@755" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLAT2.ITM~			~override/XGPLAT2.ITM~
  SAY NAME2 @756
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@757" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLAT3.ITM~			~override/XGPLAT3.ITM~
  SAY NAME2 @758
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@759" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLA30.ITM~			~override/XGPLA30.ITM~
  SAY NAME2 @760
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@571" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLAT4.ITM~			~override/XGPLAT4.ITM~
  SAY NAME2 @761
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@762" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLAT5.ITM~			~override/XGPLAT5.ITM~
  SAY NAME2 @763
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@764" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGplat6.ITM~			~override/XGplat6.ITM~
  SAY NAME2 @765
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@766" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLAT7.ITM~			~override/XGPLAT7.ITM~
  SAY NAME2 @767
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@768" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLAT8.ITM~			~override/XGPLAT8.ITM~
  SAY NAME2 @769
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@770" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLAT9.ITM~			~override/XGPLAT9.ITM~
  SAY NAME2 @771
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@772" END
  
COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLAM1.ITM~			~override/XGPLAM1.ITM~
  SAY NAME2 @773
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@774" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPLD.ITM~			~override/XGPLD.ITM~
  SAY NAME1 @775 
  SAY NAME2 @775 
  SAY UNIDENTIFIED_DESC @776 
  SAY DESC @776 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGplet1.ITM~			~override/XGplet1.ITM~
  SAY UNIDENTIFIED_DESC @777 
  SAY DESC @777 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGplet.ITM~			~override/XGplet.ITM~
  SAY UNIDENTIFIED_DESC @777 
  SAY DESC @777 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGprc1.ITM~			~override/XGprc1.ITM~
  SAY NAME1 @778 
  SAY NAME2 @778 
  SAY UNIDENTIFIED_DESC @658 
  SAY DESC @658 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGPRC.ITM~			~override/XGPRC.ITM~
  SAY NAME1 @778 
  SAY NAME2 @778 
  SAY UNIDENTIFIED_DESC @658 
  SAY DESC @658 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGprt1.ITM~			~override/XGprt1.ITM~
  SAY NAME1 @778 
  SAY NAME2 @778 
  SAY UNIDENTIFIED_DESC @658 
  SAY DESC @658 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGprt.ITM~			~override/XGprt.ITM~
  SAY NAME1 @778
  SAY NAME2 @778
  SAY UNIDENTIFIED_DESC @658
  SAY DESC @658

COPY ~weidu_external/Paladins-of-Faerun/Items/XGQI1.ITM~			~override/XGQI1.ITM~
  SAY NAME1 @779
  SAY NAME2 @779
  SAY UNIDENTIFIED_DESC @667
  SAY DESC @667

COPY ~weidu_external/Paladins-of-Faerun/Items/XGQI2.ITM~			~override/XGQI2.ITM~
  SAY NAME1 @779 
  SAY NAME2 @779 
  SAY UNIDENTIFIED_DESC @780 
  SAY DESC @780 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGQI3.ITM~			~override/XGQI3.ITM~
  SAY NAME1 @779 
  SAY NAME2 @779 
  SAY UNIDENTIFIED_DESC @667 
  SAY DESC @667 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGqic.ITM~			~override/XGqic.ITM~
  SAY NAME1 @781 
  SAY NAME2 @781 
  SAY UNIDENTIFIED_DESC @782 
  SAY DESC @782 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGqi.ITM~			~override/XGqi.ITM~
  SAY NAME1 @781 
  SAY NAME2 @781 
  SAY UNIDENTIFIED_DESC @782 
  SAY DESC @782 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGqit.ITM~			~override/XGqit.ITM~
  SAY NAME1 @781 
  SAY NAME2 @781 
  SAY UNIDENTIFIED_DESC @782 
  SAY DESC @782 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGQKEY.ITM~			~override/XGQKEY.ITM~
  SAY NAME1 @783 
  SAY NAME2 @783 
  SAY UNIDENTIFIED_DESC @784 
  SAY DESC @784
  
COPY ~weidu_external/Paladins-of-Faerun/Items/XGQKEY.ITM~			~override/XGKEY302.ITM~
  SAY NAME1 @1641 
  SAY NAME2 @1641 
  SAY UNIDENTIFIED_DESC @1642 
  SAY DESC @1642 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGRING1.ITM~			~override/XGRING1.ITM~
  SAY NAME2 @785
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@786" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGRING2.ITM~			~override/XGRING2.ITM~
  SAY NAME2 @787
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@788" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGRING3.ITM~			~override/XGRING3.ITM~
  SAY NAME2 @789
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@790" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGRING.ITM~			~override/XGRING.ITM~
  SAY NAME1 @791 
  SAY NAME2 @791 
  SAY UNIDENTIFIED_DESC @792 
  SAY DESC @792 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGS.ITM~			~override/XGS.ITM~
  SAY NAME1 #6646 
  SAY NAME2 #6646 
  SAY UNIDENTIFIED_DESC #6738 
  SAY DESC #6738 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSAK.ITM~			~override/XGSAK.ITM~
  SAY NAME1 @793 
  SAY NAME2 @793 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSCR.ITM~			~override/XGSCR.ITM~
  SAY NAME1 @794 
  SAY NAME2 @794 
  SAY DESC @795 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSHLD1.ITM~			~override/XGSHLD1.ITM~
  SAY NAME2 @796
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@797" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSHLD2.ITM~			~override/XGSHLD2.ITM~
  SAY NAME2 @798
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@799" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSHLD3.ITM~			~override/XGSHLD3.ITM~
  SAY NAME2 @800
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@801" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSHLD4.ITM~			~override/XGSHLD4.ITM~
  SAY NAME2 @802
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@803" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSHL.ITM~			~override/XGSHL.ITM~
  SAY DESC #6819

COPY ~weidu_external/Paladins-of-Faerun/Items/XGsk.ITM~			~override/XGsk.ITM~
  SAY UNIDENTIFIED_DESC @804 
  SAY DESC @804 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGspb.ITM~			~override/XGspb.ITM~
  SAY NAME1 @805 
  SAY NAME2 @805 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSTAR1.ITM~			~override/XGSTAR1.ITM~
  SAY NAME1 @806
  SAY NAME2 @806
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@807" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@807" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSTAR2.ITM~			~override/XGSTAR2.ITM~
  SAY NAME1 @806
  SAY NAME2 @808
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@809" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@810" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSTAR3.ITM~			~override/XGSTAR3.ITM~
  SAY NAME1 @806
  SAY NAME2 @811
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@809" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@812" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSTAR4.ITM~			~override/XGSTAR4.ITM~
  SAY NAME1 @806
  SAY NAME2 @813
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@809" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@814" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSTAR5.ITM~			~override/XGSTAR5.ITM~
  SAY NAME1 @806
  SAY NAME2 @815
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@809" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@816" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSTAR6.ITM~			~override/XGSTAR6.ITM~
  SAY NAME1 @806
  SAY NAME2 @817
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@809" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@818" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSTAR7.ITM~			~override/XGSTAR7.ITM~
  SAY NAME1 @806
  SAY NAME2 @819
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@809" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@820" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSTAR.ITM~			~override/XGSTAR.ITM~ // same as XGSTAR1 but not used and not accurate
  SAY NAME1 @806 
  SAY NAME2 @806 
  SAY UNIDENTIFIED_DESC @807 
  SAY DESC @807 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSUD01.ITM~			~override/XGSUD01.ITM~
  SAY NAME1 @821
  SAY NAME2 @821
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@822" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@822" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSUD02.ITM~			~override/XGSUD02.ITM~
  SAY NAME1 @821
  SAY NAME2 @823
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@822" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@824" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSUD03.ITM~			~override/XGSUD03.ITM~
  SAY NAME1 @821
  SAY NAME2 @825
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@822" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@826" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSUD04.ITM~			~override/XGSUD04.ITM~
  SAY NAME1 @821
  SAY NAME2 @827
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@822" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@828" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSUD05.ITM~			~override/XGSUD05.ITM~
  SAY NAME1 @821
  SAY NAME2 @829
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@822" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@830" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSUD06.ITM~			~override/XGSUD06.ITM~
  SAY NAME1 @821
  SAY NAME2 @831
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@822" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@832" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSUD07.ITM~			~override/XGSUD07.ITM~
  SAY NAME1 @821
  SAY NAME2 @833
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@822" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@834" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWFJ.ITM~			~override/XGSWFJ.ITM~
  SAY NAME1 @835
  SAY NAME2 @835
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@836" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@837" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWOJ.ITM~			~override/XGSWOJ.ITM~// not used and not accurate

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWOR1.ITM~			~override/XGSWOR1.ITM~
  SAY NAME2 @838
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@839" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWOR2.ITM~			~override/XGSWOR2.ITM~
  SAY NAME2 @840
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@841" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWOR3.ITM~			~override/XGSWOR3.ITM~
  SAY NAME2 @842
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@843" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWOR4.ITM~			~override/XGSWOR4.ITM~
  SAY NAME2 @844
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@845" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWOR5.ITM~			~override/XGSWOR5.ITM~
  SAY NAME2 @846
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@847" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWOR6.ITM~			~override/XGSWOR6.ITM~
  SAY NAME2 @848
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@849" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWOR7.ITM~			~override/XGSWOR7.ITM~
  SAY NAME2 @850
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@851" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWOR8.ITM~			~override/XGSWOR8.ITM~
  SAY NAME2 @852
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@853" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWOR9.ITM~			~override/XGSWOR9.ITM~
  SAY NAME2 @854
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@855" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO10.ITM~			~override/XGSWO10.ITM~
  SAY NAME2 @856
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@857" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO11.ITM~			~override/XGSWO11.ITM~
  SAY NAME2 @858
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@859" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO12.ITM~			~override/XGSWO12.ITM~
  SAY NAME2 @860
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@861" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO13.ITM~			~override/XGSWO13.ITM~
  SAY NAME2 @862
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@863" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO14.ITM~			~override/XGSWO14.ITM~
  SAY NAME2 @864
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@865" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO15.ITM~			~override/XGSWO15.ITM~
  SAY NAME2 @866
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@867" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO16.ITM~			~override/XGSWO16.ITM~
  SAY NAME2 @868
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@869" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO17.ITM~			~override/XGSWO17.ITM~
  SAY NAME2 @870
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@871" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO18.ITM~			~override/XGSWO18.ITM~
  SAY NAME2 @872
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@873" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO19.ITM~			~override/XGSWO19.ITM~
  SAY NAME2 @874
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@875" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO20.ITM~			~override/XGSWO20.ITM~
  SAY NAME2 @876
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@877" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGSWO21.ITM~			~override/XGSWO21.ITM~
  SAY NAME2 @878
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@879" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGTGBOD.ITM~			~override/XGTGBOD.ITM~
  SAY NAME1 @880
  SAY NAME2 @880
  SAY DESC @881


COPY ~weidu_external/Paladins-of-Faerun/Items/XGTRBL.ITM~			~override/XGTRBL.ITM~
  SAY NAME1 @882
  SAY NAME2 @882
  SAY UNIDENTIFIED_DESC @883
  SAY DESC @883 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGTRI1.ITM~			~override/XGTRI1.ITM~
  SAY NAME1 @884
  SAY NAME2 @884
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@885" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@885" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGTRI2.ITM~			~override/XGTRI2.ITM~
  SAY NAME1 @884
  SAY NAME2 @886
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@885" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@887" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGTRI3.ITM~			~override/XGTRI3.ITM~
  SAY NAME1 @884
  SAY NAME2 @888
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@885" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@889" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGTRI4.ITM~			~override/XGTRI4.ITM~
  SAY NAME1 @884
  SAY NAME2 @890
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@885" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@891" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGTRI5.ITM~			~override/XGTRI5.ITM~
  SAY NAME1 @884
  SAY NAME2 @892
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@885" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@893" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGTRI6.ITM~			~override/XGTRI6.ITM~
  SAY NAME1 @884
  SAY NAME2 @894
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@885" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@895" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGTRI7.ITM~			~override/XGTRI7.ITM~
  SAY NAME1 @884
  SAY NAME2 @896
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_undesc_to_update = "@885" END
  LPF ~GW_WRITE_EE_ITM_DESCRIPTIONS~ STR_VAR GW_desc_to_update = "@897" END

COPY ~weidu_external/Paladins-of-Faerun/Items/XGTRW.ITM~			~override/XGTRW.ITM~
  SAY NAME2 @898 
  SAY DESC @899 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGUKEY.ITM~			~override/XGUKEY.ITM~
  SAY UNIDENTIFIED_DESC @900 
  SAY DESC @900 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGVR.ITM~			~override/XGVR.ITM~
  SAY NAME1 @901 
  SAY NAME2 @902 
  SAY DESC @903 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGWA.ITM~			~override/XGWA.ITM~
  SAY NAME1 @904
  SAY NAME2 @904
  SAY UNIDENTIFIED_DESC @905
  SAY DESC @905

COPY ~weidu_external/Paladins-of-Faerun/Items/XGWAND1.ITM~		~override/XGWAND1.ITM~
  SAY NAME2 @906 
  SAY DESC @907 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGWAND2.ITM~		~override/XGWAND2.ITM~
  SAY NAME2 @908
  SAY DESC @909

COPY ~weidu_external/Paladins-of-Faerun/Items/XGWAND3.ITM~		~override/XGWAND3.ITM~
  SAY NAME2 @910
  SAY DESC @911

COPY ~weidu_external/Paladins-of-Faerun/Items/XGWH.ITM~			~override/XGWH.ITM~
  SAY NAME1 @912
  SAY NAME2 @912
  SAY UNIDENTIFIED_DESC @913
  SAY DESC @913

COPY ~weidu_external/Paladins-of-Faerun/Items/XGWOLFF.ITM~		~override/XGWOLFF.ITM~

COPY ~weidu_external/Paladins-of-Faerun/Items/XGWRD1.ITM~			~override/XGWRD1.ITM~
  SAY NAME1 @914 
  SAY NAME2 @914 
  SAY UNIDENTIFIED_DESC @915 
  SAY DESC @915 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGWRG.ITM~			~override/XGWRG.ITM~
  SAY UNIDENTIFIED_DESC @916 
  SAY DESC @916 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGZAT1.ITM~			~override/XGZAT1.ITM~
  SAY NAME1 @917 
  SAY NAME2 @917 
  SAY UNIDENTIFIED_DESC @918 
  SAY DESC @918 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGZAT2.ITM~			~override/XGZAT2.ITM~
  SAY NAME1 @917 
  SAY NAME2 @917 
  SAY UNIDENTIFIED_DESC @918 
  SAY DESC @918 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGZAT3.ITM~			~override/XGZAT3.ITM~
  SAY NAME1 @917 
  SAY NAME2 @917 
  SAY UNIDENTIFIED_DESC @918 
  SAY DESC @918 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGZAT4.ITM~			~override/XGZAT4.ITM~
  SAY NAME1 @917 
  SAY NAME2 @917 
  SAY UNIDENTIFIED_DESC @918 
  SAY DESC @918 

COPY ~weidu_external/Paladins-of-Faerun/Items/XGZAT5.ITM~			~override/XGZAT5.ITM~
  SAY NAME1 @917
  SAY NAME2 @917
  SAY UNIDENTIFIED_DESC @918
  SAY DESC @918

COPY ~weidu_external/Paladins-of-Faerun/Items/XGZAT6.ITM~			~override/XGZAT6.ITM~
  SAY NAME1 @917
  SAY NAME2 @917
  SAY UNIDENTIFIED_DESC @918
  SAY DESC @918

COPY ~weidu_external/Paladins-of-Faerun/Items/XGZAT.ITM~			~override/XGZAT.ITM~
  SAY NAME1 @917
  SAY NAME2 @917
  SAY UNIDENTIFIED_DESC @918
  SAY DESC @918

COPY ~weidu_external/Paladins-of-Faerun/Items/XGOLBRAC.ITM~			~override/XGOLBRAC.ITM~
  SAY NAME1 #6797 // ~Gantelets~
  SAY NAME2 @930
  SAY UNIDENTIFIED_DESC #6798 // ~Not impemented yet~
  SAY DESC @931
