ACTION_IF FILE_EXISTS_IN_GAME ~bgee.lua~ BEGIN
	PRINT ~Aeras cheat for Paladin of Faerun~
	COPY_EXISTING ~bgee.lua~ ~override/bgee.lua~

	// CheatsAreas pour Paladin of Faerun
	PATCH_DEFINE_ASSOCIATIVE_ARRAY strings_pof BEGIN
	~{"OH7200", "Hexxat - Bottom Right Quarter (Zakhara)"},~                             => 100000

END

    PATCH_PHP_EACH strings_pof AS find => replace_ref BEGIN
        SPRINT replace (AT replace_ref)
        REPLACE_TEXTUALLY ~%find%~ ~%replace%~
    END
END

ACTION_IF GAME_IS ~eet~ AND FILE_EXISTS_IN_GAME ~bgee.lua~ BEGIN
	PRINT ~Aeras cheat for Paladin of Faerun EET~
	COPY_EXISTING ~bgee.lua~ ~override/bgee.lua~

	// CheatsAreas pour Paladin of Faerun
	PATCH_DEFINE_ASSOCIATIVE_ARRAY strings_pof_eet BEGIN
	~\({"XG0020",.*"},\)~                             => 100001
	~\({"XG0120",.*"},\)~                             => 100002
	~\({"XG0820",.*"},\)~                             => 100003
	~\({"XG0520",.*"},\)~                             => 100004
	~\({"XG0620",.*"},\)~                             => 100005
	~\({"XG0320",.*"},\)~                             => 100006

END

    PATCH_PHP_EACH strings_pof_eet AS find => replace_ref BEGIN
        SPRINT replace (AT replace_ref)
        REPLACE_TEXTUALLY ~%find%~ ~%replace%~
    END
END

ACTION_IF GAME_IS ~bgt~ AND FILE_EXISTS_IN_GAME ~bgee.lua~ BEGIN
	PRINT ~Aeras cheat for Paladin of Faerun BGT~
	COPY_EXISTING ~bgee.lua~ ~override/bgee.lua~

	// CheatsAreas pour Paladin of Faerun
	PATCH_DEFINE_ASSOCIATIVE_ARRAY strings_pof_bgt BEGIN
	~\({"XG0020",.*"},\)~                             => 100007
	~\({"XG0120",.*"},\)~                             => 100008
	~\({"XG0820",.*"},\)~                             => 100009
	~\({"XG0520",.*"},\)~                             => 100010
	~\({"XG0620",.*"},\)~                             => 100011
	~\({"XG0320",.*"},\)~                             => 100012

END

    PATCH_PHP_EACH strings_pof_bgt AS find => replace_ref BEGIN
        SPRINT replace (AT replace_ref)
        REPLACE_TEXTUALLY ~%find%~ ~%replace%~
    END
END

///////////////////////////// Alternative
/*

ACTION_IF NOT GAME_IS ~eet bgt~ AND  FILE_EXISTS_IN_GAME ~bgee.lua~ BEGIN
	PRINT ~Aeras cheat for Paladin of Faerun~
	COPY_EXISTING ~bgee.lua~ ~override/bgee.lua~

	// CheatsAreas pour Paladin of Faerun
	PATCH_DEFINE_ASSOCIATIVE_ARRAY strings BEGIN
	~{"OH7200", "Hexxat - Bottom Right Quarter (Zakhara)"},~                             => 100000

END

    PATCH_PHP_EACH strings AS find => replace_ref BEGIN
        SPRINT replace (AT replace_ref)
        REPLACE_TEXTUALLY ~%find%~ ~%replace%~
    END
END

ACTION_IF GAME_IS ~eet~ AND FILE_EXISTS ~Paladins-of-Faerun/Languages/%LANGUAGE%/SETUP-Paladins-of-Faerun.tra~ BEGIN
	PRINT ~Aeras cheat for Paladin of Faerun~
	COPY_EXISTING ~Paladins-of-Faerun/Languages/%LANGUAGE%/SETUP-Paladins-of-Faerun.tra~ ~weidu_external/Paladins-of-Faerun/Languages/autotra/%LANGUAGE%/SETUP-Paladins-of-Faerun.tra~

	// CheatsAreas pour Paladin of Faerun
	PATCH_DEFINE_ASSOCIATIVE_ARRAY strings BEGIN
	~XG0020~                             => ~BG0200~
	~XG0120~                             => ~BG0119~
	~XG0820~                             => ~BG0121~
	~XG0520~                             => ~BG0006~
	~XG0620~                             => ~BG0111~
	~XG0320~                             => ~BG0137~

END

    PATCH_PHP_EACH strings AS find => replace_ref BEGIN
        SPRINT replace (AT replace_ref)
        REPLACE_TEXTUALLY ~%find%~ ~%replace%~
    END

  ACTION_IF FILE_EXISTS_IN_GAME ~bgee.lua~ BEGIN
	PRINT ~Aeras cheat for Paladin of Faerun~
	COPY_EXISTING ~bgee.lua~ ~override/bgee.lua~

	// CheatsAreas pour Paladin of Faerun
	PATCH_DEFINE_ASSOCIATIVE_ARRAY strings BEGIN
	~{"OH7200", "Hexxat - Bottom Right Quarter (Zakhara)"},~                             => 100000

END

    PATCH_PHP_EACH strings AS find => replace_ref BEGIN
        SPRINT replace (AT replace_ref)
        REPLACE_TEXTUALLY ~%find%~ ~%replace%~
    END
  END
END


ACTION_IF GAME_IS ~bgt~ AND FILE_EXISTS ~Paladins-of-Faerun/Languages/%LANGUAGE%/SETUP-Paladins-of-Faerun.tra~ BEGIN
	PRINT ~Aeras cheat for Paladin of Faerun~
	COPY_EXISTING ~Paladins-of-Faerun/Languages/%LANGUAGE%/SETUP-Paladins-of-Faerun.tra~ ~weidu_external/Paladins-of-Faerun/Languages/autotra/%LANGUAGE%/SETUP-Paladins-of-Faerun.tra~

	// CheatsAreas pour Paladin of Faerun
	PATCH_DEFINE_ASSOCIATIVE_ARRAY strings BEGIN
	~XG0020~                             => ~AR7300~
	~XG0120~                             => ~AR7219~
	~XG0820~                             => ~AR7220~
	~XG0520~                             => ~ARA006~
	~XG0620~                             => ~AR7211~
	~XG0320~                             => ~AR7237~

END

    PATCH_PHP_EACH strings AS find => replace_ref BEGIN
        SPRINT replace (AT replace_ref)
        REPLACE_TEXTUALLY ~%find%~ ~%replace%~
    END

  ACTION_IF FILE_EXISTS_IN_GAME ~bgee.lua~ BEGIN
	PRINT ~Aeras cheat for Paladin of Faerun~
	COPY_EXISTING ~bgee.lua~ ~override/bgee.lua~

	// CheatsAreas pour Paladin of Faerun
	PATCH_DEFINE_ASSOCIATIVE_ARRAY strings BEGIN
	~{"OH7200", "Hexxat - Bottom Right Quarter (Zakhara)"},~                             => 100000

END

    PATCH_PHP_EACH strings AS find => replace_ref BEGIN
        SPRINT replace (AT replace_ref)
        REPLACE_TEXTUALLY ~%find%~ ~%replace%~
    END
  END
END
*/
