

PRINT ~Install Animations~

// Install all animations. It is only valid for ee.
ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN
    // First: install animation that exists in ee animate.ids, but ini file and animation files themselved might not
    // exist in the game.
    ACTION_FOR_EACH animation IN
        ~iwd_barbarian_warrior_brown~
        ~iwd_barbarian_warrior_red~
        ~iwd_barbarian_warrior_tan~
        ~iwd2_drider_female~
        ~iwd2_drider_male~
       //~abishai_white~
       //~bonebat~
       //~bugbear~
       //~feyr~
       //~feyr_greater~
       //~giant_frost~
       //~giant_hill~
       //~golem_iron_iwd~
       //~harpy~
       //~iwd_cyclops~
       //~iwd_ghost~
       //~iwd_shadow_large~
       //~iwd_troll_snow~
       //~iwd_wight_gray~
       //~lizard_king~
       //~lizard_man~
       //~wererat~
    BEGIN
        ACTION_BASH_FOR ~Paladins-of-Faerun/Animations/%animation%~ ~.+$~ BEGIN
            // We copy only the files we do need.
            ACTION_IF NOT FILE_EXISTS_IN_GAME ~%BASH_FOR_FILE%~ BEGIN
                COPY_LARGE ~%BASH_FOR_FILESPEC%~ ~override/%BASH_FOR_FILE%~
            END
        END
    END
END // ...END... To remove if next block is used
/*
    ACTION_DEFINE_ASSOCIATIVE_ARRAY anim_to_min_slot BEGIN
        ~amel_pc_nwn~ => ~0xe000~
        ~shadow_small_murky~ => ~0xe000~
        ~garolyth_pst~ => ~0xe000~
        ~grillig_pst~ => ~0xe000~
        ~gronk_pst~ => ~0xe000~
        ~shadow_pst~ => ~0xe000~
        ~shadow_mark_iii_pst~ => ~0xe000~
        ~shadow_greater_pst~ => ~0xe000~
        ~larval_pst~ => ~0xe000~
        ~giant_skeleton_pst~ => ~0xe000~
        ~hag_shadow~ => ~0xe000~
    END

    ACTION_PHP_EACH anim_to_min_slot AS animation => min_slot
    BEGIN
        OUTER_TEXT_SPRINT upp_anim ~%animation%~
        ACTION_TO_UPPER upp_anim
        OUTER_SET slot = IDS_OF_SYMBOL (~animate~ ~%upp_anim%~)
        ACTION_IF slot<0 BEGIN
            LAF ~FIND_FREE_ANIM_SLOT~ INT_VAR slotMin = min_slot STR_VAR GWFormatAnim = BG2SPLIT RET slot END
            ACTION_IF (slot < 0) BEGIN
                WARN ~!!! WARNING : No free creature animation slot found for %animation% !!!~
            END ELSE BEGIN
                LAF ~TO_HEX_NUMBER~ INT_VAR value = slot minDigits = 4 RET hexNumber END
                APPEND ~animate.ids~ ~0x%hexNumber% %upp_anim%~
                CLEAR_IDS_MAP

                ACTION_BASH_FOR ~Paladins-of-Faerun/Animations//%animation%~ ~.+$~ BEGIN
                    // We copy only the files we do need.
                    ACTION_IF NOT FILE_EXISTS_IN_GAME ~%BASH_FOR_FILE%~ BEGIN
                        ACTION_TO_LOWER %BASH_FOR_FILE%
                        COPY_LARGE ~%BASH_FOR_FILESPEC%~ ~override/%BASH_FOR_FILE%~
                    END
                END
                COPY ~Paladins-of-Faerun/Animations//ini/%animation%.ini~ ~override/%hexNumber%.ini~
            END
        END
    END
END
*/

ACTION_IF (NOT GAME_IS ~bg2ee eet~) BEGIN
    // First: install animation that exists in ee animate.ids, but ini file and animation files themselved might not
    // exist in the game.
    ACTION_FOR_EACH animation IN
        ~UNKNOWN~
    BEGIN
		ACTION_IF NOT FILE_EXISTS_IN_GAME ~4001.ini~ BEGIN
			COPY ~Paladins-of-Faerun/Animations/NONE/4001.ini~ ~override/4001.ini~
				ACTION_IF NOT FILE_EXISTS_IN_GAME ~SNONE.BAM~ BEGIN
					COPY ~Paladins-of-Faerun/Animations/NONE/SNONE.BAM~ ~override/SNONE.BAM~
            END
        END
    END
END
