
//////////////////////////////////
// Setup Areas
//////////////////////////////////

/*
MKDIR ~weidu_external/PoFQuestPack/Areas~

ACTION_BASH_FOR ~PoFQuestPack/Areas~ ~^.+$~ BEGIN

PRINT ~         ~
PRINT ~START creature in areas~
PRINT ~         ~

  COPY ~%BASH_FOR_FILESPEC%~ ~weidu_external/%BASH_FOR_FILESPEC%~
    LPM UPDATE_POF_CRE_NAMES_ON_AREA
	// Area-macros.tpa
PRINT ~         ~
PRINT ~END creature in areas~
PRINT ~         ~

END
*/
/*
 // NOT WORKING NOT FOUND YET


ACTION_BASH_FOR ~weidu_external/PoFQuestPack/Areas~ ~^.+$~ BEGIN

PRINT ~         ~
PRINT ~START Containers in areas~
PRINT ~         ~

  COPY ~%BASH_FOR_FILESPEC%~ ~%BASH_FOR_FILESPEC%~
    LPM UPDATE_POF_ITEM_NAMES_ON_CONT
	// Area-macros.tpa
	
PRINT ~         ~
PRINT ~END Containers in areas~
PRINT ~         ~

END
*/

COPY ~weidu_external/PoFQuestPack/Areas/XG0000.ARE~         ~override/XG0000.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0001.ARE~         ~override/XG0001.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0002.ARE~         ~override/XG0002.ARE~

ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0003.ARE~			~override/XG0003.ARE~
  SAY 0x26b0 @398
  SAY 0x2838 @1000
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1001)
				STR_VAR 
				fj_cre_resref0 = ~SHADOW01~
				fj_structure_type = interrupts
				fj_name  = XGSHAd
			END

END       

ACTION_IF (GAME_IS ~tob bgt~) BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0003.ARE~			~override/XG0003.ARE~
  SAY 0x26b0 @398
  SAY 0x2838 @1000
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1001)
				STR_VAR 
				fj_cre_resref0 = ~SHADOW01~
				fj_structure_type = interrupts
				fj_name  = XGSHAd
			END

END    

COPY ~weidu_external/PoFQuestPack/Areas/XG0004.ARE~         ~override/XG0004.ARE~
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1002)
				STR_VAR 
				fj_cre_resref0 = ~HGWAR01~
				fj_structure_type = interrupts
				fj_name  = GIANT
			END

ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0007.ARE~         ~override/XG0007.ARE~
  SAY 0x3104 @399
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1001)
				STR_VAR 
				fj_cre_resref0 = ~XGGOB4~
				fj_structure_type = interrupts
				fj_name  = XGGOB
			END

END       

ACTION_IF (GAME_IS ~tob bgt~) BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0007.ARE~         ~override/XG0007.ARE~
  SAY 0x3104 @399
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1001)
				STR_VAR 
				fj_cre_resref0 = ~XGGOB4~
				fj_structure_type = interrupts
				fj_name  = XGGOB
			END

END    

COPY ~weidu_external/PoFQuestPack/Areas/XG0009.ARE~         ~override/XG0009.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0012.ARE~         ~override/XG0012.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0013.ARE~         ~override/XG0013.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0014.ARE~         ~override/XG0014.ARE~
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1003)
				STR_VAR 
				fj_cre_resref0 = ~SIRINE01~
				fj_structure_type = interrupts
				fj_name  = SIREN
			END

COPY ~weidu_external/PoFQuestPack/Areas/XG0015.ARE~         ~override/XG0015.ARE~
	LPF fj_are_structure
		INT_VAR
		fj_type			= 1    // Info point
		fj_box_left		= 1655
		fj_box_top		= 340
		fj_box_right	= 1699
		fj_box_bottom	= 400
		fj_cursor_idx	= 22   // curseur ?
		fj_info_point_strref  = RESOLVE_STR_REF (@400)
		fj_loc_x		= 1677
		fj_loc_y		= 370
		fj_vertex_0		= 1656 + (400 << 16)
		fj_vertex_1		= 1699 + (393 << 16)
		fj_vertex_2		= 1699 + (339 << 16)
		fj_vertex_3		= 1655 + (345 << 16)
		fj_vertex_4		= 1656 + (400 << 16)
		STR_VAR
		fj_structure_type	= region
		fj_name				= info01
		END
  ADD_MAP_NOTE #1650 #236 ~gray~ #5386 // maison abandonnée.
  ADD_MAP_NOTE #310 #538 ~red~ @999

// Valid colors include: gray, orange, blue, darkblue, lightgray, RED, YELLOW, GREEN, DEFAULT, 
//  ADD_MAP_NOTE #xCoord  #yCoord  ~Note Color~ ~Text~

COPY ~weidu_external/PoFQuestPack/Areas/XG0016.ARE~			~override/XG0016.ARE~
	LPF fj_are_structure
		INT_VAR
		fj_type			= 1    // Info point
		fj_box_left		= 1013
		fj_box_top		= 4
		fj_box_right	= 1160
		fj_box_bottom	= 86
		fj_cursor_idx	= 22   // curseur ?
		fj_info_point_strref  = RESOLVE_STR_REF (@1600)
		fj_loc_x		= 1083
		fj_loc_y		= 42
		fj_vertex_0		= 1137 + (4 << 16)
		fj_vertex_1		= 1153 + (47 << 16)
		fj_vertex_2		= 1160 + (69 << 16)
		fj_vertex_3		= 1099 + (86 << 16)
		fj_vertex_4		= 1062 + (84 << 16)
		fj_vertex_5		= 1030 + (54 << 16)
		fj_vertex_6		= 1013 + (4 << 16)
		STR_VAR
		fj_structure_type	= region
		fj_name				= info16
		END
  ADD_MAP_NOTE #1083 #42 ~red~ @1501

COPY ~weidu_external/PoFQuestPack/Areas/XG0017.ARE~			~override/XG0017.ARE~
  ADD_MAP_NOTE #1448 #3453 ~red~ @1005
  ADD_MAP_NOTE #1711 #1541 ~red~ @1006
  ADD_MAP_NOTE #1553 #1150 ~BLUE~ @1007

COPY ~weidu_external/PoFQuestPack/Areas/XG0018.ARE~         ~override/XG0018.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0019.ARE~         ~override/XG0019.ARE~

//ACTION_IF NOT GAME_IS ~bgt eet~ BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0020.ARE~         ~override/XG0020.ARE~
  WRITE_ASCII 0x94 ~XG0020~ #8
  LPF fj_are_structure
    INT_VAR
      fj_variable_value = 1
    STR_VAR
      fj_structure_type = "variable"
      fj_name           = "XGNEWGAME_SOA"
  END
  
//END

ACTION_IF GAME_IS ~bgt eet~ BEGIN

	COPY_EXISTING ~%NBaldursGate%.ARE~			~override/%NBaldursGate%.ARE~
		WRITE_ASCIIE 0x94 ~%NBaldursGate_BCS%~ #8 // Use WRITE_ASCIIE for evaluate the integer
		LPF fj_are_structure
			INT_VAR
			fj_variable_value = 1
			STR_VAR
			fj_structure_type = "variable"
			fj_name           = "POFAREA"
		END  

	COPY_EXISTING ~%NBaldursGate_DucalPalace_L1%.ARE~			~override/%NBaldursGate_DucalPalace_L1%.ARE~
		WRITE_ASCIIE 0x94 ~%NBaldursGate_DucalPalace_L1_BCS%~ #8 // Use WRITE_ASCIIE for evaluate the integer
	LPF fj_are_structure
		INT_VAR
		fj_variable_value = 1
		STR_VAR
		fj_structure_type = "variable"
		fj_name           = "POFAREA"
	END
	LPF fj_are_structure
		INT_VAR
		fj_type			= 2    // travel
		fj_box_left		= 314
		fj_box_top		= 94
		fj_box_right	= 534
		fj_box_bottom	= 284
		fj_cursor_idx	= 28   // 30 door 28 stairs
		fj_info_point_strref  = RESOLVE_STR_REF (@1620)
		fj_loc_x		= 660
		fj_loc_y		= 532
		fj_vertex_0		= 475 + (94 << 16)
		fj_vertex_1		= 423 + (145 << 16)
		fj_vertex_2		= 366 + (191 << 16)
		fj_vertex_3		= 314 + (245 << 16)
		fj_vertex_4		= 374 + (284 << 16)
		fj_vertex_5		= 481 + (190 << 16)
		fj_vertex_6		= 534 + (147 << 16)
		fj_vertex_7		= 534 + (147 << 16)
		fj_vertex_8		= 534 + (146 << 16)
		STR_VAR
		fj_structure_type	= region
		fj_name				= TravelXG0720
		fj_destination_area	= XG0720 // Code de la carte
		fj_destination_name	= ExitBG0108
		END 
	LPF fj_are_structure 
		INT_VAR 
		fj_loc_x = 624 
		fj_loc_y = 236 
		fj_orientation = 14 
		STR_VAR 
		fj_structure_type = actor
		fj_name = "XGFLAM10" 
		fj_cre_resref = "XGFLAM10" 
		fj_dlg_resref = "XGFLAM10"
		fj_bcs_class = ~XGFLAM10~
	END
      LPF fj_are_structure
        INT_VAR
          fj_loc_x = 347
          fj_loc_y = 305
          //fj_orientation = 0
        STR_VAR
          fj_structure_type = entrance
          fj_name = EntranceBG0108
      END
END

/*
INFO POINT STRUCTURE
	LPF fj_are_structure
		INT_VAR
		fj_type			= 1    // Info point
		fj_box_left		= 1013
		fj_box_top		= 4
		fj_box_right	= 1160
		fj_box_bottom	= 86
		fj_cursor_idx	= 22   // curseur ?
		fj_info_point_strref  = RESOLVE_STR_REF (@1600)
		fj_loc_x		= 1083
		fj_loc_y		= 42
		fj_vertex_0		= 1137 + (4 << 16)
		fj_vertex_1		= 1153 + (47 << 16)
		fj_vertex_2		= 1160 + (69 << 16)
		fj_vertex_3		= 1099 + (86 << 16)
		fj_vertex_4		= 1062 + (84 << 16)
		fj_vertex_5		= 1030 + (54 << 16)
		fj_vertex_6		= 1013 + (4 << 16)
		STR_VAR
		fj_structure_type	= region
		fj_name				= info16
		END  
*/

COPY ~weidu_external/PoFQuestPack/Areas/XG0024.ARE~         ~override/XG0024.ARE~         
  SAY 0x2884 @401 
  SAY 0x2b94 @402 
  SAY 0x2D1C @1008

COPY ~weidu_external/PoFQuestPack/Areas/XG0025.ARE~         ~override/XG0025.ARE~
  SAY 0x1390 @1008        

COPY ~weidu_external/PoFQuestPack/Areas/XG0026.ARE~         ~override/XG0026.ARE~
  SAY 0x28B0 @1009
  SAY 0x28E4 @1009
  SAY 0x2918 @1010          

COPY ~weidu_external/PoFQuestPack/Areas/XG0028.ARE~         ~override/XG0028.ARE~
	LPF fj_are_structure
		INT_VAR
		fj_type			= 0    // Proximity trigge
		fj_box_left		= 416
		fj_box_top		= 1055
		fj_box_right	= 569
		fj_box_bottom	= 1151
		fj_cursor_idx	= 0   // curseur ?
		fj_flags	= BIT1 | BIT3 | BIT6  //
		//fj_info_point_strref  = RESOLVE_STR_REF (@1011) // See XGGT004.baf
		fj_trap_detect = 50
		fj_trap_remove = 50
		fj_trap_active = 1
		fj_trap_status  = 0
		fj_loc_x		= 487
		fj_loc_y		= 1102
		fj_vertex_0		= 416 + (1100 << 16)
		fj_vertex_1		= 494 + (1151 << 16)
		fj_vertex_2		= 569 + (1100 << 16)
		fj_vertex_3		= 482 + (1055 << 16)
		STR_VAR
		fj_structure_type	= region
		fj_name				= InfoPoint4
		fj_reg_script = XGGT004
		END
	LPF fj_are_structure
		INT_VAR
		fj_type			= 0    // Proximity trigge
		fj_box_left		= 214
		fj_box_top		= 1140
		fj_box_right	= 454
		fj_box_bottom	= 1278
		fj_cursor_idx	= 0   // curseur ?
		fj_flags	= BIT1 | BIT6  //
		//fj_info_point_strref  = RESOLVE_STR_REF (~Auras-tu la faiblesse d’esprit de tenter la traversée ?~) // See XGGT004.baf
		fj_loc_x		= 325
		fj_loc_y		= 1219
		fj_trap_active = 1
		fj_trap_status  = 0
		fj_vertex_0		= 214 + (1220 << 16)
		fj_vertex_1		= 423 + (1278 << 16)
		fj_vertex_2		= 454 + (1185 << 16)
		fj_vertex_3		= 360 + (1140 << 16)
		STR_VAR
		fj_structure_type	= region
		fj_name				= InfoPoint3
		fj_reg_script = XGGT003
		END
  ADD_MAP_NOTE #2777 #554 ~VIOLET~ @1012  

COPY ~weidu_external/PoFQuestPack/Areas/XG0029.ARE~         ~override/XG0029.ARE~         
  SAY 0x1bc4 @409  // Temple Entrance  InfoTrigger
  SAY 0x1e10 @404  // Accès sous le moulin InfoTrigger
  SAY 0x205C @1014 // Sacred Stone InfoTrigger
  SAY 0x2120 @1017  // Taverne des trois carafes InfoTrigger
  SAY 0x2890 @405 // Taverne des trois carafes MapNote
  SAY 0x2828 @1015 // Sacred Stone MapNote
  SAY 0x285c @1016  // Sacred Temple MapNote
  SAY 0x1d4c @401 // Il n'y a rien à voir par ici InfoTrigger
  SAY 0x21e4 @424 // Temple d'Ilmater
  SAY 0x28C8 @1018  // Cimetière MapNote
  ADD_MAP_NOTE #1730 #680 ~BLUE~ @424

COPY ~weidu_external/PoFQuestPack/Areas/XG0030.ARE~         ~override/XG0030.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0033.ARE~         ~override/XG0033.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0034.ARE~         ~override/XG0034.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0039.ARE~         ~override/XG0039.ARE~         
  SAY 0x339c @406 
  SAY 0x3460 @406
  SAY 0x3854 @1019 

COPY ~weidu_external/PoFQuestPack/Areas/XG0040.ARE~         ~override/XG0040.ARE~         
  SAY 0x2334 @401 
  SAY 0x23f8 @401 

COPY ~weidu_external/PoFQuestPack/Areas/XG0041.ARE~         ~override/XG0041.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0045.ARE~         ~override/XG0045.ARE~         
  SAY 0x5240 @407 
  SAY 0x58EC @1020

COPY ~weidu_external/PoFQuestPack/Areas/XG0046.ARE~         ~override/XG0046.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0047.ARE~         ~override/XG0047.ARE~
  SAY 0x16A0 @1021 
  SAY 0x1764 @1022         

COPY ~weidu_external/PoFQuestPack/Areas/XG0048.ARE~         ~override/XG0048.ARE~
// SAY 0x45A8 ~~  North Gate
// SAY 0x45DC ~~  East Gate
  ADD_MAP_NOTE #3174 #2336 ~BLUE~ #11693 // Taverne
  ADD_MAP_NOTE #3451 #1132 ~BLUE~ #8470 // Échoppe
  ADD_MAP_NOTE #1477 #1069 ~red~ @1500 // Demeure du Seigneur Nasher
  ADD_MAP_NOTE #1728 #2008 ~red~ #48371 // Maison abandonnée

COPY ~weidu_external/PoFQuestPack/Areas/XG0049.ARE~         ~override/XG0049.ARE~
  SAY 0x2444 @408 

COPY ~weidu_external/PoFQuestPack/Areas/XG0050.ARE~         ~override/XG0050.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0052.ARE~         ~override/XG0052.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0053.ARE~         ~override/XG0053.ARE~
// SAY 0x3104 ~~
// SAY 0x31C8 ~~
// SAY 0x3350 ~~
// SAY 0x3414 ~~
// SAY 0x3B80 @1022
// SAY 0x3BB4 ~~
// SAY 0x3BE8 ~~
// SAY 0x3C1C ~~

COPY ~weidu_external/PoFQuestPack/Areas/XG0054.ARE~			~override/XG0054.ARE~
  ADD_MAP_NOTE #2745 #1228 ~red~ @1006

COPY ~weidu_external/PoFQuestPack/Areas/XG0055.ARE~			~override/XG0055.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0056.ARE~			~override/XG0056.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0057.ARE~         ~override/XG0057.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0058.ARE~         ~override/XG0058.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0059.ARE~         ~override/XG0059.ARE~         
  SAY 0x2270 @410 

COPY ~weidu_external/PoFQuestPack/Areas/XG0060.ARE~         ~override/XG0060.ARE~
	LPF fj_are_structure
		INT_VAR
		fj_type			= 1    // Info point
		fj_box_left		= 530
		fj_box_top		= 162
		fj_box_right	= 611
		fj_box_bottom	= 296
		fj_cursor_idx	= 22   // curseur ?
		fj_info_point_strref  = RESOLVE_STR_REF (@411)
		fj_loc_x		= 570
		fj_loc_y		= 229
		fj_vertex_0		= 574 + (296 << 16)
		fj_vertex_1		= 544 + (287 << 16)
		fj_vertex_2		= 530 + (238 << 16)
		fj_vertex_3		= 550 + (218 << 16)
		fj_vertex_4		= 578 + (165 << 16)
		fj_vertex_5		= 596 + (161 << 16)
		fj_vertex_6		= 609 + (189 << 16)
		fj_vertex_7		= 611 + (222 << 16)
		fj_vertex_8		= 583 + (274 << 16)
		fj_vertex_9		= 574 + (296 << 16)
		STR_VAR
		fj_structure_type	= region
		fj_name				= info01
		END
	LPF fj_are_structure
		INT_VAR
		fj_type			= 1    // Info point
		fj_box_left		= 1072
		fj_box_top		= 624
		fj_box_right	= 1185
		fj_box_bottom	= 728
		fj_cursor_idx	= 22   // curseur ?
		fj_info_point_strref  = RESOLVE_STR_REF (@411)
		fj_loc_x		= 1128
		fj_loc_y		= 676
		fj_vertex_0		= 1072 + (705 << 16)
		fj_vertex_1		= 1102 + (728 << 16)
		fj_vertex_2		= 1185 + (648 << 16)
		fj_vertex_3		= 1172 + (630 << 16)
		fj_vertex_4		= 1155 + (623 << 16)
		fj_vertex_5		= 1126 + (624 << 16)
		fj_vertex_6		= 1094 + (668 << 16)
		fj_vertex_7		= 1072 + (705 << 16)
		STR_VAR
		fj_structure_type	= region
		fj_name				= info02
		END

COPY ~weidu_external/PoFQuestPack/Areas/XG0061.ARE~         ~override/XG0061.ARE~
  ADD_MAP_NOTE #2089 #1137 ~red~ @1024

COPY ~weidu_external/PoFQuestPack/Areas/XG0062.ARE~         ~override/XG0062.ARE~
  SAY 0x27C4 @1024
  SAY 0x27F8 @1025
  SAY 0x282C @1026 
  SAY 0x2860 @1027         

COPY ~weidu_external/PoFQuestPack/Areas/XG0063.ARE~         ~override/XG0063.ARE~
  SAY 0x2D9C @1028
  SAY 0x2DD0 @1029 
  SAY 0x2E04 @1030
  SAY 0x2E38 @1031
  SAY 0x2E6C @1032
  SAY 0x2EA0 @1033         

COPY ~weidu_external/PoFQuestPack/Areas/XG0064.ARE~         ~override/XG0064.ARE~
  ADD_MAP_NOTE #930 #120 ~gray~ @1024
  ADD_MAP_NOTE #3090 #180 ~gray~ @1036
  ADD_MAP_NOTE #2580 #2450 ~gray~ @1037
  ADD_MAP_NOTE #2640 #1725 ~blue~ @1034 
  ADD_MAP_NOTE #1660 #2216 ~gray~ @1035
  ADD_MAP_NOTE #1410 #1400 ~green~ @1008

COPY ~weidu_external/PoFQuestPack/Areas/XG0065.ARE~         ~override/XG0065.ARE~
  SAY 0x23E0 @1038         

COPY ~weidu_external/PoFQuestPack/Areas/XG0066.ARE~         ~override/XG0066.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0067.ARE~         ~override/XG0067.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0068.ARE~         ~override/XG0068.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0069.ARE~         ~override/XG0069.ARE~
  SAY 0x495C @1039 
  SAY 0x4960 @1040         

COPY ~weidu_external/PoFQuestPack/Areas/XG0070.ARE~         ~override/XG0070.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0071.ARE~         ~override/XG0071.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0072.ARE~         ~override/XG0072.ARE~
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1001)
				STR_VAR 
				fj_cre_resref0 = ~MUMMY~
				fj_structure_type = interrupts
				fj_name  = MUMIE
			END               

COPY ~weidu_external/PoFQuestPack/Areas/XG0073.ARE~         ~override/XG0073.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0075.ARE~         ~override/XG0075.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0076.ARE~         ~override/XG0076.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0077.ARE~         ~override/XG0077.ARE~
  SAY 0x20C8 @1001         

COPY ~weidu_external/PoFQuestPack/Areas/XG0078.ARE~         ~override/XG0078.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0079.ARE~         ~override/XG0079.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0080.ARE~         ~override/XG0080.ARE~
  ADD_MAP_NOTE #3441 #346 ~blue~ @1042 // Sanctuaire
  ADD_MAP_NOTE #1783 #1315 ~blue~ @929 // Temple of Shevarash
  ADD_MAP_NOTE #890 #510 ~blue~ @1041 // Forgeron

COPY ~weidu_external/PoFQuestPack/Areas/XG0081.ARE~         ~override/XG0081.ARE~   
  ADD_MAP_NOTE #2788 #387 ~blue~ @1008 // Auberge
  ADD_MAP_NOTE #2561 #3078 ~blue~ @1022 // Merchant
  ADD_MAP_NOTE #3449 #770 ~orange~ @155 // Monastère
  ADD_MAP_NOTE #3443 #3628 ~gray~ @1009 // Sortie de la ville    

COPY ~weidu_external/PoFQuestPack/Areas/XG1081.ARE~         ~override/XG1081.ARE~   
  ADD_MAP_NOTE #2788 #387 ~blue~ @1008 // Auberge
  ADD_MAP_NOTE #2561 #3078 ~blue~ @1022 // Merchant
  ADD_MAP_NOTE #3443 #3628 ~gray~ @1009 // Sortie de la ville

COPY ~weidu_external/PoFQuestPack/Areas/XG0082.ARE~         ~override/XG0082.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0083.ARE~         ~override/XG0083.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0084.ARE~         ~override/XG0084.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0101.ARE~         ~override/XG0101.ARE~         
  SAY 0x1280 @398 

COPY ~weidu_external/PoFQuestPack/Areas/XG0112.ARE~         ~override/XG0112.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0114.ARE~         ~override/XG0114.ARE~     

ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0115.ARE~         ~override/XG0115.ARE~
  ADD_MAP_NOTE #1421 #2237 ~red~ @1045
  SAY 0x17c0 @1043
  SAY 0x17c4 @1044

END       

ACTION_IF (GAME_IS ~tob bgt~) BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0115.ARE~         ~override/XG0115.ARE~
  ADD_MAP_NOTE #1421 #2237 ~red~ @1045
  SAY 0x16A0 @1043
  SAY 0x16A4 @1044

END    

COPY ~weidu_external/PoFQuestPack/Areas/XG0116.ARE~         ~override/XG0116.ARE~
  ADD_MAP_NOTE #290 #232 ~GREEN~ @1046
  ADD_MAP_NOTE #1505 #567 ~red~ @1047

COPY ~weidu_external/PoFQuestPack/Areas/XG0117.ARE~         ~override/XG0117.ARE~         
  SAY 0x1f40 @412 

COPY ~weidu_external/PoFQuestPack/Areas/XG0118.ARE~         ~override/XG0118.ARE~         
  SAY 0x1cd4 @413         

//ACTION_IF NOT GAME_IS ~bgt eet~ BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0120.ARE~         ~override/XG0120.ARE~
  WRITE_ASCII 0x94 ~XG0120~ #8

//END

COPY ~weidu_external/PoFQuestPack/Areas/XG0124.ARE~         ~override/XG0124.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0126.ARE~         ~override/XG0126.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0128.ARE~         ~override/XG0128.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0129.ARE~         ~override/XG0129.ARE~    
	LPF ALTER_AREA_REGION
		INT_VAR
		info_point   = RESOLVE_STR_REF (@186)
		STR_VAR
		region_name	= XGStatue
		END           

COPY ~weidu_external/PoFQuestPack/Areas/XG0130.ARE~         ~override/XG0130.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0133.ARE~         ~override/XG0133.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0139.ARE~         ~override/XG0139.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0140.ARE~         ~override/XG0140.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0141.ARE~         ~override/XG0141.ARE~ 

COPY ~weidu_external/PoFQuestPack/Areas/XG0145.ARE~         ~override/XG0145.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0146.ARE~         ~override/XG0146.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0147.ARE~         ~override/XG0147.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0148.ARE~         ~override/XG0148.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0149.ARE~         ~override/XG0149.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0150.ARE~         ~override/XG0150.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0152.ARE~         ~override/XG0152.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0153.ARE~         ~override/XG0153.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0154.ARE~         ~override/XG0154.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0156.ARE~         ~override/XG0156.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0158.ARE~         ~override/XG0158.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0159.ARE~         ~override/XG0159.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0160.ARE~         ~override/XG0160.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0161.ARE~         ~override/XG0161.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0162.ARE~         ~override/XG0162.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0163.ARE~         ~override/XG0163.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0164.ARE~         ~override/XG0164.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0165.ARE~         ~override/XG0165.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0166.ARE~         ~override/XG0166.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0167.ARE~         ~override/XG0167.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0168.ARE~         ~override/XG0168.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0169.ARE~         ~override/XG0169.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0170.ARE~         ~override/XG0170.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0171.ARE~         ~override/XG0171.ARE~         
  SAY 0x1c88 @416
  SAY 0x21C4 @1001 

COPY ~weidu_external/PoFQuestPack/Areas/XG0172.ARE~         ~override/XG0172.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0176.ARE~         ~override/XG0176.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0177.ARE~         ~override/XG0177.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0178.ARE~         ~override/XG0178.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0179.ARE~         ~override/XG0179.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0180.ARE~         ~override/XG0180.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0181.ARE~         ~override/XG0181.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0182.ARE~         ~override/XG0182.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0183.ARE~         ~override/XG0183.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0184.ARE~         ~override/XG0184.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0201.ARE~         ~override/XG0201.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0202.ARE~         ~override/XG0202.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0203.ARE~         ~override/XG0203.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0211.ARE~         ~override/XG0211.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0212.ARE~         ~override/XG0212.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0213.ARE~         ~override/XG0213.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0214.ARE~         ~override/XG0214.ARE~       
	WRITE_ASCII 0x94 ~XG0214~ (8)

COPY ~weidu_external/PoFQuestPack/Areas/XG0215.ARE~         ~override/XG0215.ARE~
  SAY 0x35CC @1043
  SAY 0x3694 @1048          

COPY ~weidu_external/PoFQuestPack/Areas/XG0217.ARE~         ~override/XG0217.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0219.ARE~         ~override/XG0219.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0220.ARE~         ~override/XG0220.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0224.ARE~         ~override/XG0224.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0226.ARE~         ~override/XG0226.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0228.ARE~         ~override/XG0228.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0229.ARE~         ~override/XG0229.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0230.ARE~         ~override/XG0230.ARE~        

COPY ~weidu_external/PoFQuestPack/Areas/XG0239.ARE~         ~override/XG0239.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0240.ARE~         ~override/XG0240.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0245.ARE~         ~override/XG0245.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0246.ARE~         ~override/XG0246.ARE~
  SAY 0x3784 @1049          

COPY ~weidu_external/PoFQuestPack/Areas/XG0247.ARE~         ~override/XG0247.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0256.ARE~         ~override/XG0256.ARE~         
  SAY 0x1454 @417 

COPY ~weidu_external/PoFQuestPack/Areas/XG0259.ARE~         ~override/XG0259.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0261.ARE~         ~override/XG0261.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0262.ARE~         ~override/XG0262.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0263.ARE~         ~override/XG0263.ARE~
// SAY 0x4BD4 @1001          

COPY ~weidu_external/PoFQuestPack/Areas/XG0264.ARE~         ~override/XG0264.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0265.ARE~         ~override/XG0265.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0266.ARE~         ~override/XG0266.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0269.ARE~         ~override/XG0269.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0271.ARE~         ~override/XG0271.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0276.ARE~         ~override/XG0276.ARE~
  SAY 0x258C @1050
  SAY 0x25C0 @1051         

COPY ~weidu_external/PoFQuestPack/Areas/XG0278.ARE~         ~override/XG0278.ARE~
  SAY 0x1E54 @1050
  SAY 0x1E88 @1051          

COPY ~weidu_external/PoFQuestPack/Areas/XG0279.ARE~         ~override/XG0279.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0280.ARE~         ~override/XG0280.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0281.ARE~         ~override/XG0281.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0284.ARE~         ~override/XG0284.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0301.ARE~         ~override/XG0301.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0302.ARE~         ~override/XG0302.ARE~         
  SAY 0x2664 @418 
  SAY 0x2728 @418
  SAY 0x5A18 @1001
  SAY 0x5A1C @1001 

COPY ~weidu_external/PoFQuestPack/Areas/XG0311.ARE~         ~override/XG0311.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0312.ARE~         ~override/XG0312.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0313.ARE~         ~override/XG0313.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0315.ARE~         ~override/XG0315.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0317.ARE~         ~override/XG0317.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0319.ARE~         ~override/XG0319.ARE~         

//ACTION_IF NOT GAME_IS ~bgt eet~ BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0320.ARE~         ~override/XG0320.ARE~
  WRITE_ASCII 0x94 ~XG0320~ #8

//END

COPY ~weidu_external/PoFQuestPack/Areas/XG0324.ARE~         ~override/XG0324.ARE~        

COPY ~weidu_external/PoFQuestPack/Areas/XG0328.ARE~         ~override/XG0328.ARE~
  SAY 0x4250 @419

COPY ~weidu_external/PoFQuestPack/Areas/XG0329.ARE~         ~override/XG0329.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0330.ARE~         ~override/XG0330.ARE~

ACTION_IF (GAME_IS ~bg2ee eet~) BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0339.ARE~         ~override/XG0339.ARE~
  SAY 0x259C @1001
  SAY 0x25b0 @1001
END       

ACTION_IF (GAME_IS ~tob bgt~) BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0339.ARE~         ~override/XG0339.ARE~
  SAY 0x25EC @1001 

END

COPY ~weidu_external/PoFQuestPack/Areas/XG0340.ARE~         ~override/XG0340.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0345.ARE~         ~override/XG0345.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0346.ARE~         ~override/XG0346.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0347.ARE~         ~override/XG0347.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0359.ARE~         ~override/XG0359.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG0362.ARE~         ~override/XG0362.ARE~
  SAY 0x4b0 @420

COPY ~weidu_external/PoFQuestPack/Areas/XG0363.ARE~         ~override/XG0363.ARE~         
  SAY 0x9b4 @421 

COPY ~weidu_external/PoFQuestPack/Areas/XG0364.ARE~         ~override/XG0364.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0365.ARE~         ~override/XG0365.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0369.ARE~         ~override/XG0369.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0371.ARE~         ~override/XG0371.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0380.ARE~         ~override/XG0380.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0381.ARE~         ~override/XG0381.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0384.ARE~         ~override/XG0384.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0401.ARE~         ~override/XG0401.ARE~
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1052)
				STR_VAR 
				fj_cre_resref0 = ~XGMOON~
				fj_structure_type = interrupts
				fj_name  = XGELF
			END       

COPY ~weidu_external/PoFQuestPack/Areas/XG0402.ARE~         ~override/XG0402.ARE~
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1001)
				STR_VAR 
				fj_cre_resref0 = ~XGDUER~
				fj_structure_type = interrupts
				fj_name  = XGDuer
			END      

COPY ~weidu_external/PoFQuestPack/Areas/XG0403.ARE~         ~override/XG0403.ARE~         
  SAY 0x2bb4 @422 

COPY ~weidu_external/PoFQuestPack/Areas/XG0411.ARE~         ~override/XG0411.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0412.ARE~         ~override/XG0412.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0413.ARE~         ~override/XG0413.ARE~         
  SAY 0x354 @423 

COPY ~weidu_external/PoFQuestPack/Areas/XG0414.ARE~         ~override/XG0414.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0415.ARE~         ~override/XG0415.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0417.ARE~         ~override/XG0417.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0419.ARE~         ~override/XG0419.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0420.ARE~         ~override/XG0420.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0424.ARE~         ~override/XG0424.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0426.ARE~         ~override/XG0426.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0429.ARE~         ~override/XG0429.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0439.ARE~         ~override/XG0439.ARE~
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1001)
				STR_VAR 
				fj_cre_resref0 = ~SKELWA01~
				fj_structure_type = interrupts
				fj_name  = KOST
			END              

COPY ~weidu_external/PoFQuestPack/Areas/XG0440.ARE~         ~override/XG0440.ARE~ 

COPY ~weidu_external/PoFQuestPack/Areas/XG0446.ARE~         ~override/XG0446.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0447.ARE~         ~override/XG0447.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0462.ARE~         ~override/XG0462.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0464.ARE~         ~override/XG0464.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0480.ARE~         ~override/XG0480.ARE~
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1001)
				STR_VAR 
				fj_cre_resref0 = ~ELEARL01~
				fj_structure_type = interrupts
				fj_name  = elearl01
			END                 

COPY ~weidu_external/PoFQuestPack/Areas/XG0481.ARE~         ~override/XG0481.ARE~
  ADD_MAP_NOTE #35 #2012 ~orange~ @1018 // Cimetière
  ADD_MAP_NOTE #680 #3642 ~gray~ #48376 // Sortie

COPY ~weidu_external/PoFQuestPack/Areas/XG04N1.ARE~         ~override/XG04N1.ARE~
  WRITE_ASCII 0x94 ~XG04N1~ #8
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1052)
				STR_VAR 
				fj_cre_resref0 = ~XGMOON~
				fj_structure_type = interrupts
				fj_name  = XGELF
			END

COPY ~weidu_external/PoFQuestPack/Areas/XG04N2.ARE~         ~override/XG04N2.ARE~
  WRITE_ASCII 0x94 ~XG04N2~ #8
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1001)
				STR_VAR 
				fj_cre_resref0 = ~XGDUER~
				fj_structure_type = interrupts
				fj_name  = XGDuer
			END

COPY ~weidu_external/PoFQuestPack/Areas/XG04N3.ARE~         ~override/XG04N3.ARE~         
  SAY 0x2bb4 @422 
  WRITE_ASCII 0x94 ~XG04N3~ #8

COPY ~weidu_external/PoFQuestPack/Areas/XG0511.ARE~         ~override/XG0511.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0515.ARE~         ~override/XG0515.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0517.ARE~         ~override/XG0517.ARE~         

//ACTION_IF NOT GAME_IS ~bgt eet~ BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0520.ARE~         ~override/XG0520.ARE~
  WRITE_ASCII 0x94 ~XG0520~ #8

//END

COPY ~weidu_external/PoFQuestPack/Areas/XG0524.ARE~         ~override/XG0524.ARE~         
  SAY 0x4b0 @401 

COPY ~weidu_external/PoFQuestPack/Areas/XG0526.ARE~         ~override/XG0526.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0529.ARE~         ~override/XG0529.ARE~
  SAY 0x1604 @1001

COPY ~weidu_external/PoFQuestPack/Areas/XG0539.ARE~         ~override/XG0539.ARE~
  SAY 0x1D88 @1001         

COPY ~weidu_external/PoFQuestPack/Areas/XG0547.ARE~         ~override/XG0547.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0548.ARE~         ~override/XG0548.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0562.ARE~         ~override/XG0562.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0564.ARE~         ~override/XG0564.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0580.ARE~         ~override/XG0580.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0581.ARE~         ~override/XG0581.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0615.ARE~         ~override/XG0615.ARE~         

//ACTION_IF NOT GAME_IS ~bgt eet~ BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0620.ARE~         ~override/XG0620.ARE~
  WRITE_ASCII 0x94 ~XG0620~ #8

//END

COPY ~weidu_external/PoFQuestPack/Areas/XG0624.ARE~         ~override/XG0624.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0629.ARE~         ~override/XG0629.ARE~ 

COPY ~weidu_external/PoFQuestPack/Areas/XG0639.ARE~         ~override/XG0639.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0647.ARE~         ~override/XG0647.ARE~         
  SAY 0x16c0 @427 

COPY ~weidu_external/PoFQuestPack/Areas/XG0648.ARE~         ~override/XG0648.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0662.ARE~         ~override/XG0662.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0680.ARE~         ~override/XG0680.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0681.ARE~         ~override/XG0681.ARE~ 
  ADD_MAP_NOTE #680 #3642 ~gray~ #48376 // Sortie        

COPY ~weidu_external/PoFQuestPack/Areas/XG0701.ARE~         ~override/XG0701.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0702.ARE~         ~override/XG0702.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0715.ARE~         ~override/XG0715.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0720.ARE~         ~override/XG0720.ARE~
  WRITE_ASCII 0x94 ~XG0720~ #8
  SAY 0x1170 @428
  SAY 0x1234 @428
  SAY 0x13bc @429
  
  
ACTION_IF GAME_IS ~bgt eet~ BEGIN
	COPY_EXISTING ~XG0720.ARE~ ~override~
		LPF fj_are_structure
			INT_VAR
			fj_type			= 2    // travel
			fj_box_left		= 401
			fj_box_top		= 1373
			fj_box_right	= 521
			fj_box_bottom	= 1564
			fj_cursor_idx	= 30   // 30 door 28 stairs
			fj_loc_x		= 461
			fj_loc_y		= 1468
			fj_vertex_0		= 429 + (1372 << 16)
			fj_vertex_1		= 401 + (1500 << 16)
			fj_vertex_2		= 498 + (1564 << 16)
			fj_vertex_3		= 521 + (1437 << 16)
			fj_vertex_4		= 429 + (1372 << 16)
			STR_VAR
			fj_structure_type	= region
			fj_name				= TravelBG0108
			fj_destination_area	= EVAL ~%NBaldursGate_DucalPalace_L1%~ // Code de la carte
			fj_destination_name	= EntranceBG0108
		END
      LPF fj_are_structure
        INT_VAR
          fj_loc_x = 542
          fj_loc_y = 1413
          //fj_orientation = 0
        STR_VAR
          fj_structure_type = entrance
          fj_name = ExitBG0108
      END
		LPF fj_are_structure
			INT_VAR
			fj_type			= 2    // travel
			fj_box_left		= 401
			fj_box_top		= 1373
			fj_box_right	= 521
			fj_box_bottom	= 1564
			fj_cursor_idx	= 30   // 30 door 28 stairs
			fj_loc_x		= 461
			fj_loc_y		= 1468
			fj_vertex_0		= 429 + (1372 << 16)
			fj_vertex_1		= 401 + (1500 << 16)
			fj_vertex_2		= 498 + (1564 << 16)
			fj_vertex_3		= 521 + (1437 << 16)
			fj_vertex_4		= 429 + (1372 << 16)
			STR_VAR
			fj_structure_type	= region
			fj_name				= TravelXG0720
			fj_destination_area	= XG0020 // Code de la carte
			fj_destination_name	= ExitXG0720
		END
END ELSE BEGIN
	COPY_EXISTING ~XG0720.ARE~ ~override~
		LPF fj_are_structure
			INT_VAR
			fj_type			= 2    // travel
			fj_box_left		= 401
			fj_box_top		= 1373
			fj_box_right	= 521
			fj_box_bottom	= 1564
			fj_cursor_idx	= 30   // 30 door 28 stairs
			fj_loc_x		= 461
			fj_loc_y		= 1468
			fj_vertex_0		= 429 + (1372 << 16)
			fj_vertex_1		= 401 + (1500 << 16)
			fj_vertex_2		= 498 + (1564 << 16)
			fj_vertex_3		= 521 + (1437 << 16)
			fj_vertex_4		= 429 + (1372 << 16)
			STR_VAR
			fj_structure_type	= region
			fj_name				= TravelXG0720
			fj_destination_area	= XG0020 // Code de la carte
			fj_destination_name	= ExitXG0720
		END
END

COPY ~weidu_external/PoFQuestPack/Areas/XG0729.ARE~         ~override/XG0729.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0747.ARE~         ~override/XG0747.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0748.ARE~         ~override/XG0748.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0762.ARE~         ~override/XG0762.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0764.ARE~         ~override/XG0764.ARE~         
  SAY 0x5c0 @430 

COPY ~weidu_external/PoFQuestPack/Areas/XG0780.ARE~         ~override/XG0780.ARE~ 
  SAY 0x3648 @1053        

COPY ~weidu_external/PoFQuestPack/Areas/XG0801.ARE~         ~override/XG0801.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0803.ARE~         ~override/XG0803.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0815.ARE~         ~override/XG0815.ARE~   
  ADD_MAP_NOTE #1138 #2166 ~red~ @1501 // Vers la Passe du Géant              

//ACTION_IF NOT GAME_IS ~bgt eet~ BEGIN

COPY ~weidu_external/PoFQuestPack/Areas/XG0820.ARE~         ~override/XG0820.ARE~
  WRITE_ASCII 0x94 ~XG0820~ #8
  //SAY 0x41C @1001 useless normaly         

//END

COPY ~weidu_external/PoFQuestPack/Areas/XG0829.ARE~         ~override/XG0829.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0864.ARE~         ~override/XG0864.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0880.ARE~         ~override/XG0880.ARE~   
  ADD_MAP_NOTE #3984 #826 ~red~ @101 // Vieux dragon      

COPY ~weidu_external/PoFQuestPack/Areas/XG0901.ARE~         ~override/XG0901.ARE~
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1054)
				STR_VAR 
				fj_cre_resref0 = ~XGUNPAL~
				fj_structure_type = interrupts
				fj_name  = XGUNPal
			END

COPY ~weidu_external/PoFQuestPack/Areas/XG0902.ARE~         ~override/XG0902.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0903.ARE~         ~override/XG0903.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0920.ARE~         ~override/XG0920.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0964.ARE~         ~override/XG0964.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG0A80.ARE~         ~override/XG0A80.ARE~
  ADD_MAP_NOTE #3441 #346 ~blue~ @1042 // Sanctuaire
  ADD_MAP_NOTE #1783 #1315 ~blue~ @929 // Temple of Shevarash
  ADD_MAP_NOTE #890 #510 ~blue~ @1041 // Forgeron

COPY ~weidu_external/PoFQuestPack/Areas/XG1020.ARE~         ~override/XG1020.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG1034.ARE~         ~override/XG1034.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG1053.ARE~         ~override/XG1053.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG1057.ARE~         ~override/XG1057.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG1080.ARE~         ~override/XG1080.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG1120.ARE~         ~override/XG1120.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG1134.ARE~         ~override/XG1134.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG1220.ARE~         ~override/XG1220.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG1234.ARE~         ~override/XG1234.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG1319.ARE~         ~override/XG1319.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG2057.ARE~         ~override/XG2057.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG4000.ARE~         ~override/XG4000.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG4001.ARE~         ~override/XG4001.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG8100.ARE~         ~override/XG8100.ARE~
  ADD_MAP_NOTE #2788 #387 ~blue~ @1008 // Auberge
  ADD_MAP_NOTE #3449 #770 ~orange~ @155 // Monastère
  ADD_MAP_NOTE #3443 #3628 ~gray~ @1009 // Sortie de la ville   

COPY ~weidu_external/PoFQuestPack/Areas/XG8101.ARE~         ~override/XG8101.ARE~
  ADD_MAP_NOTE #2788 #387 ~blue~ @1008 // Auberge
  ADD_MAP_NOTE #3443 #3628 ~gray~ @1009 // Sortie de la ville

COPY ~weidu_external/PoFQuestPack/Areas/XG8103.ARE~         ~override/XG8103.ARE~         

COPY ~weidu_external/PoFQuestPack/Areas/XG8104.ARE~         ~override/XG8104.ARE~    
  ADD_MAP_NOTE #35 #2012 ~orange~ @1018 // Cimetière
  ADD_MAP_NOTE #680 #3642 ~gray~ #48376 // Sortie

COPY ~weidu_external/PoFQuestPack/Areas/XG8200.ARE~         ~override/XG8200.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG8201.ARE~         ~override/XG8201.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG8300.ARE~         ~override/XG8300.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG8301.ARE~         ~override/XG8301.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG8400.ARE~         ~override/XG8400.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XG8500.ARE~         ~override/XG8500.ARE~
  ADD_MAP_NOTE #680 #3642 ~gray~ #48376 // Sortie

COPY ~weidu_external/PoFQuestPack/Areas/XGA180.ARE~         ~override/XGA180.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XGA280.ARE~         ~override/XGA280.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XGA380.ARE~			~override/XGA380.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XGA480.ARE~         ~override/XGA480.ARE~
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1001)
				STR_VAR 
				fj_cre_resref0 = ~ELEARL01~
				fj_structure_type = interrupts
				fj_name  = elearl01
			END

COPY ~weidu_external/PoFQuestPack/Areas/XGB180.ARE~         ~override/XGB180.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XGKAR1.ARE~         ~override/XGKAR1.ARE~
  SAY 0x1060 @431

COPY ~weidu_external/PoFQuestPack/Areas/XGKAR2.ARE~         ~override/XGKAR2.ARE~
  SAY 0x1280 @431

COPY ~weidu_external/PoFQuestPack/Areas/XGRA01.ARE~         ~override/XGRA01.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XGRA03.ARE~         ~override/XGRA03.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XGRA04.ARE~         ~override/XGRA04.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XGRA06.ARE~         ~override/XGRA06.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XGRA08.ARE~         ~override/XGRA08.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XGTORM.ARE~         ~override/XGTORM.ARE~

COPY ~weidu_external/PoFQuestPack/Areas/XGUMOD.ARE~			~override/XGUMOD.ARE~
  SAY 0x3040 @432
			LPF fj_are_structure
				INT_VAR 
				fj_cre_strref0  =  RESOLVE_STR_REF (@1001)
				fj_cre_strref1  =  RESOLVE_STR_REF (@1001)
				STR_VAR 
				fj_cre_resref0 = ~XGBMT~
				fj_cre_resref1 = ~XGBMT~
				fj_structure_type = interrupts
				fj_name  = XGBMT
			END
