IF
  OnCreation()
  Global("EnteredXG0030","XG0030",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredXG0030","XG0030",1)
    ClearAllActions()
    StartCutSceneMode()
    HideGUI()
    CreateCreature("XGFNAS",[3062.2592],15)  // ~Слуга Хельма~
    MoveViewPoint([3124.2674],SLOW)
    Wait(5)
    DisplayStringHead("XGFNAS",@0)  // @0
    Wait(4)
    ActionOverride("XGFNAS",EscapeArea())
    Wait(2)
    AddexperienceParty(10000)
    UnhideGUI()
    EndCutSceneMode()
END

