IF
  Global("Reveal0083","PF0083",0)
  PartyHasItem("CDMOD")  // ~Кинжал~
THEN
  RESPONSE #100
    SetGlobal("Reveal0083","PF0083",1)
    StartCutSceneMode()
    HideGUI()
    PlaySound("Mus2mod")
    CreateCreature("CHFMOD",[3483.572],0)  // ~Убийца-Цирикист~
    ActionOverride("CHFMOD",MoveToPoint([3731.424]))
    Wait(5)
    ActionOverride("CHFMOD",Enemy())
    EndCutSceneMode()
    UnhideGUI()
    AddexperienceParty(5000)
END

