IF
  Global("Reveal0020","PF0020",0)
  PartyHasItem("XGZAT2")  // ~Îנהונ םא אנוסע~
THEN
  RESPONSE #100
    SetGlobal("Reveal0020","PF0020",1)
    StartCutSceneMode()
    HideGUI()
    CreateCreature("XGASSBG",[3390.1570],8)  // ~Óבטיצא~
    CreateCreature("XGASSBG",[3524.1624],8)  // ~Óבטיצא~
    CreateCreature("XGASSBG",[3639.1627],8)  // ~Óבטיצא~
    TakePartyItem("XGZAT2")
    GiveItemCreate("XGZAT3",Player1,0,0,0)  // ~Îנהונ םא אנוסע~
    UnhideGUI()
    EndCutSceneMode()
END

