IF
  OnCreation()
  Global("EnteredXG0128","XG0128",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredXG0128","XG0128",1)
    ClearAllActions()
    StartCutSceneMode()
    HideGUI()
    Wait(4)
    ActionOverride(Player1,LeaveAreaLUA("XG0128","",[940.460],0))
    Wait(4)
    DisplayString("XGDRUIC",@0)  // @0
    Wait(11)
    ActionOverride("XGDRUIC",EscapeArea())
    Wait(1)
    ActionOverride(Player1,LeaveAreaLUA("XG0128","",[1929.831],0))
    UnhideGUI()
    EndCutSceneMode()
END

