IF OnCreation()
  Global("EnteredXG0162","XG0162",0)
THEN
  RESPONSE #100
    SetGlobal("EnteredXG0162","XG0162",1)    
    StartCutSceneMode()
    ClearAllActions()
    CreateCreature("s#mage2",[1250.1012],10) 
    PlaySound("XGNWN1")
    Wait(1)
    DisplayStringHead("s#mage2",@0)
    Wait(2)
    DisplayStringHead("XGNASHR", @1)
    Wait(2)
    ActionOverride("XGNASHR",StartDialogue("XGNASHR",Player1))
    EndCutSceneMode()
END

