IF
  Global("RevealXG1120","XG1120",0)
  HPLT("XGARTBG",120)  // ~Артемис~
THEN
  RESPONSE #100
    SetGlobal("RevealXG1120","XG1120",1)
    Wait(3)
    StartCutSceneMode()
    HideGUI()
    GiveItemCreate("XGKAT01",Player1,0,0,0)  // ~Zbran temnoty~
    GiveItemCreate("XGZAT5",Player1,0,0,0)  // ~Ордер на арест~
    DisplayStringHead(Player1,@0)  // @0
    ClearAllActions()
    Wait(3)
    DisplayStringHead("XGARTBG",@1)  // @1
    Wait(5)
    ActionOverride("XGARTBG",EscapeArea())
    Wait(3)
	SetGlobal("XGPoFinBG","GLOBAL",1)
    ActionOverride(Player2,LeaveAreaLUA("%NBaldursGate%","",[282.1732],0))
    ActionOverride(Player1,LeaveAreaLUA("%NBaldursGate%","",[248.1687],0))
    ActionOverride(Player3,LeaveAreaLUA("%NBaldursGate%","",[279.1645],0))
    ActionOverride(Player4,LeaveAreaLUA("%NBaldursGate%","",[361.1670],0))
    ActionOverride(Player5,LeaveAreaLUA("%NBaldursGate%","",[431.1723],0))
    ActionOverride(Player6,LeaveAreaLUA("%NBaldursGate%","",[499.1689],0))
    UnhideGUI()
    EndCutSceneMode()
END

