IF
	True()
	Global("EnteredAreaAR1005","AR1005",0)
THEN
	RESPONSE #100
		SetGlobal("EnteredAreaAR1005","AR1005",1)
		ClearAllActions()
		StartCutSceneMode()
		FadeFromColor([20.0],0)
		Explore()
		Wait(3)
		CreateCreature("XGELWIN",[904.521],0)  // ~Элвин~
		OpenDoor("DOOR05")
		Wait(1)
		ActionOverride("XGELWIN",MoveToPoint([1144.498]))
		Wait(4)
		OpenDoor("DOOR04")
		Wait(1)
		DisplayString("XGELWIN",@0)  // @0
		Wait(5)
		DisplayStringHead(Player1,@1)  // @1
		Wait(3)
		OpenDoor("DOOR03")
		OpenDoor("DOOR06")
		OpenDoor("DOOR11")
		OpenDoor("DOOR10")
		OpenDoor("SECRET03")
		DisplayString("XGELWIN",@2)  // @2
		Wait(4)
		ActionOverride("XGELWIN",MoveToPointNoInterrupt([865.601]))
		ActionOverride("XGELWIN",OpenDoor("Door07"))
		Wait(1)
		ActionOverride("XGELWIN",EscapeArea())
		UnhideGUI()
		EndCutSceneMode()
		Continue()
END


IF
	Global("XG_PoF_GetMarco","GLOBAL",1)
	Global("XGMARKinJail","AR1005",0)
THEN
	RESPONSE #100
		CreateCreature("XGMAR1",[521.752],10)  // ~Marco le voleur en prison
		CreateCreature("XGPRISON",[778.597],0)  // ~Agent de liaison
		AddMapNote([521.752],~Cellule de Marco.~)
		SetGlobal("XGMARKinJail","AR1005",1)
END


IF
	Global("XG_PoF_GetMarco","GLOBAL",4)
THEN
	RESPONSE #100
		RemoveMapNote([521.752],~Cellule de Marco.~)
		ActionOverride("XGPRISON",EscapeArea())
END
