IF
	Global("XGJOPEAS","GLOBAL",0)
	Global("NEWGAME_SOA","GLOBAL",1)
	Global("XGPoFinBG","GLOBAL",1)
	AreaCheck("BG0200")  // (PoF)  Porte de Baldur
THEN
	RESPONSE #100
		CreateCreatureObject("XGJOPEAS",Player1,0,0,0)  // Paysan // Player1
		CreateCreature("XGJOPEAS",[562.2338],SE)  // Paysan // Sud
		CreateCreature("XGJOPEAS",[1171.3119],SE)  // Paysan // Sud
		CreateCreature("XGJOPEAS",[324.841],SE)  // Paysan // Nord Ouest
		CreateCreature("XGJOPEAS",[1947.2900],SE)  // Paysan // Front palace
		CreateCreature("XGJOPEAS",[4343.1930],SE)  // Paysan // Nord East
		CreateCreature("XGJOPEAS",[3782.3065],SE)  // Paysan
		SetGlobal("XGJOPEAS","GLOBAL",1)
END

IF
	!Global("NEWGAME_SOA","GLOBAL",1)
	Global("Reveal0020","MYAREA",0)
	PartyHasItem("XGZAT2")  // ~Îנהונ םא אנוסע~
	AreaCheck("%NBaldursGate%")
THEN
  RESPONSE #100
    SetGlobal("Reveal0020","MYAREA",1)
    StartCutSceneMode()
    HideGUI()
    CreateCreature("XGASSBG",[3390.1570],8)  // ~Óבטיצא~
    CreateCreature("XGASSBG",[3524.1624],8)  // ~Óבטיצא~
    CreateCreature("XGASSBG",[3639.1627],8)  // ~Óבטיצא~
    TakePartyItem("XGZAT2")
    GiveItemCreate("XGZAT3",Player1,0,0,0)  // ~Îנהונ םא אנוסע~
    UnhideGUI()
    EndCutSceneMode()
END

IF
	!Global("NEWGAME_SOA","GLOBAL",1)
	Global("XGPoFinBG","GLOBAL",1)
	Global("XGPoFXGMIL","MYAREA",0)
	AreaCheck("%NBaldursGate%")
THEN
	RESPONSE #100
		CreateCreature("XGMIL",[3840.2483],14)  // Milicien
		CreateCreature("XGMIL",[3920.2062],8)  // Milicien
		CreateCreature("XGMIL",[4368.1547],2)  // Milicien
		CreateCreature("XGMIL",[3642.1484],0)  // Milicien
		CreateCreature("XGMIL",[2559.1320],14)  // Milicien
		CreateCreature("XGMIL",[328.1512],14)  // Milicien
		CreateCreature("XGMIL",[134.1603],14)  // Milicien
		CreateCreature("XGMIL",[2155.2838],2)  // Milicien
		CreateCreature("XGTDR",[1449.1155],0)  // Pretre
		CreateCreature("XGTDR",[1662.1154],0)  // Pretre
		CreateCreature("tanadv03",[3195.1065],0)  // Aventurier
		SetGlobal("XGPoFXGMIL","MYAREA",1)
		Continue()
END

/*
IF
	Global("NEWGAME_SOA","GLOBAL",1)
	Global("XGPoFinBG","GLOBAL",1)
	AreaCheck("BG0200")
THEN
	RESPONSE #100
		StartCutSceneMode()
		HideGUI()
		ClearAllActions()
		FadeToColor([50.0],0)
		Wait(2)
		SetGlobal("XGNEWGAME_SOA","GLOBAL",1)
		ActionOverride(Player2,LeaveAreaLUA("XG0020","",[3782.3065],8))
		ActionOverride(Player1,LeaveAreaLUA("XG0020","",[3818.3026],8))
		ActionOverride(Player3,LeaveAreaLUA("XG0020","",[3877.3112],8))
		ActionOverride(Player4,LeaveAreaLUA("XG0020","",[3802.3159],8))
		ActionOverride(Player5,LeaveAreaLUA("XG0020","",[3660.3114],8))
		ActionOverride(Player6,LeaveAreaLUA("XG0020","",[3707.3156],8))
		UnhideGUI()
		EndCutSceneMode()
END
*/

/*
IF
	Global("NEWGAME_SOA","GLOBAL",1)
	Global("XGPoFinBG","GLOBAL",1)
	Global("XGNEWGAME_SOA","GLOBAL",1)
	AreaCheck("XG0020")
THEN
	RESPONSE #100
		SetGlobal("XGNEWGAME_SOA","GLOBAL",0)
		Wait(2)
		FadeFromColor([20.0],0)
		UnhideGUI()
		EndCutSceneMode()
END
*/



/*
IF
	Global("XGPoFinBG","GLOBAL",1)
THEN
  RESPONSE #100
  TriggerActivation("EntranceXG0620",TRUE)
  	AddMapNote([2260.1047],@20)
  	AddMapNote([2769.1185],@21)
  	AddMapNote([2147.1737],@22)
  	AddMapNote([3116.2027],@23)
  	AddMapNote([3256.711],@24)
  	RemoveMapNote([2385.700],68997)
  	RemoveMapNote([2385.700],68997)
END

IF
	Global("XGPoFinBG","GLOBAL",0)
THEN
  RESPONSE #100
	TriggerActivation("EntranceXG0620",FALSE)
  	AddMapNote([3256.711],@24)
  	AddMapNote([3256.711],@24)
  	RemoveMapNote([2385.700],68997)
  	RemoveMapNote([2385.700],68997)
  	RemoveMapNote([2385.700],68997)
  	RemoveMapNote([2385.700],68997)
END
*/