IF
	PartyHasItem("XGMRBO")
	Global("XG1020_XG0720","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("XG1020_XG0720","MYAREA",1)
		ClearAllActions()
		StartCutSceneMode()
		SetGlobal("XG0720_XG1120","MYAREA",1)
		FadeFromColor([20.0],0)
		Wait(2)
		UnhideGUI()
		EndCutSceneMode()
END

IF
	!Global("NEWGAME_SOA","GLOBAL",1)
	Global("XGPoFinBG","GLOBAL",1)
	AreaCheck("XG0720")
	Global("TravelXG0720TRUE","GLOBAL",0)
THEN
	RESPONSE #100
		TriggerActivation("TravelBG0108",TRUE)
		TriggerActivation("TravelXG0720",FALSE)
		SetGlobal("TravelXG0720TRUE","GLOBAL",1)
END

IF
	Global("NEWGAME_SOA","GLOBAL",1)
	Global("XGPoFinBG","GLOBAL",1)
	AreaCheck("XG0720")
	Global("TravelXG0720FALSE","GLOBAL",0)
THEN
	RESPONSE #100
		TriggerActivation("TravelXG0720",TRUE)
		TriggerActivation("TravelBG0108",FALSE)
		SetGlobal("TravelXG0720FALSE","GLOBAL",1)
END
